In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re
import time

In [2]:
session = requests.Session()
standings_urls = {
    'PremierLeague': "https://fbref.com/en/comps/9/Premier-League-Stats",
    'Laliga': "https://fbref.com/en/comps/12/La-Liga-Stats'",
    'Bundesliga': "https://fbref.com/en/comps/20/Bundesliga-Stats",
    'SerieA': "https://fbref.com/en/comps/11/Serie-A-Stats",
    'League1': "https://fbref.com/en/comps/13/ligue-1-Stats",
    # 'BelgianProLeague' : 'https://fbref.com/en/comps/37/Belgian-Pro-League-Stats',
    # 'Eredivisie' : 'https://fbref.com/en/comps/23/Eredivisie-Stats',
    # 'PrimeiraLiga' : 'https://fbref.com/en/comps/32/Primeira-Liga-Stats',
    # 'PremierLeagueWomen' : 'https://fbref.com/en/comps/189/Womens-Super-League-Stats'
}

In [3]:
def get_team_links(b_data, L_soup):
    standings_table = L_soup.select('table.stats_table')[0]
    td_tags = standings_table.find_all('td', {"data-stat": 'team'})

    all_team_names = [a.get_text(strip=True)
                      for td in td_tags for a in td.find_all('a')]

    links = standings_table.find_all('a')
    links = [l.get("href") for l in links]
    links = [l for l in links if '/squads/' in l]
    team_urls = [f"https://fbref.com{l}" for l in links]

    team_ids = [re.search(r'/squads/([^/]+)/', t_url).group(1)
                for t_url in team_urls if re.search(r'/squads/([^/]+)/', t_url)]
    team_name_links = [t_url.split("/")[-1].replace("-Stats", "")
                       for t_url in team_urls]

    return team_urls, all_team_names, team_ids, team_name_links

In [4]:
def get_team_data(data, counter, team_name, fteam, opponent):

    if counter == 0:
        ScoresFixtures = pd.read_html(data.text, match="Scores & Fixtures")[0]
        ScoresFixtures.drop(['Match Report', 'Notes'], axis=1, inplace=True)
        fteam.append(ScoresFixtures)

    elif counter == 1:
        try:
            Shooting = pd.read_html(data.text, match="Shooting", header=1)
            # Shooting[0] = Shooting[0].rename(columns=lambda x: f'{team_name}_' + x)
            Shooting[1] = Shooting[1].rename(columns=lambda x: f'O_' + x)
            fteam.append(Shooting[0].iloc[:-1, 11:-1])
            opponent.append(Shooting[1].iloc[:-1, 11:-1])

        except Exception as e:
            print('The problem is ', e)
    elif counter == 2:
        try:
            Goalkeeping = pd.read_html(
                data.text, match="Goalkeeping", header=1)
            # Goalkeeping[0] = Goalkeeping[0].rename(columns=lambda x: f'{team_name}_' + x)
            Goalkeeping[1] = Goalkeeping[1].rename(columns=lambda x: f'O_' + x)

            Goalkeeping[0].drop('GA.1', axis=1, inplace=True)
            Goalkeeping[1].drop('O_GA.1', axis=1, inplace=True)

            fteam.append(Goalkeeping[0].iloc[:-1, 10:-1])
            opponent.append(Goalkeeping[1].iloc[:-1, 10:-1])

        except Exception as e:
            print('The problem is ', e)
    elif counter == 3:
        try:
            Passing = pd.read_html(data.text, match="Passing", header=1)
            # Passing[0] = Passing[0].rename(columns=lambda x: f'{team_name}_' + x)
            Passing[1] = Passing[1].rename(columns=lambda x: f'O_' + x)

            fteam.append(Passing[0].iloc[:-1, 10:-1])
            opponent.append(Passing[1].iloc[:-1, 10:-1])

        except Exception as e:
            print('The problem is ', e)
    elif counter == 4:
        try:
            PassTypes = pd.read_html(data.text, match="Pass Types", header=1)
            # PassTypes[0] = PassTypes[0].rename(columns=lambda x: f'{team_name}_' + x)
            PassTypes[1] = PassTypes[1].rename(columns=lambda x: f'O_' + x)

            fteam.append(PassTypes[0].iloc[:-1, 10:-1])
            opponent.append(PassTypes[1].iloc[:-1, 10:-1])

        except Exception as e:
            print('The problem is ', e)

    elif counter == 5:
        try:
            GoalShotCreation = pd.read_html(
                data.text, match="Goal and Shot Creation", header=1)
            # GoalShotCreation[0] = GoalShotCreation[0].rename(columns=lambda x: f'{team_name}_' + x)
            GoalShotCreation[1] = GoalShotCreation[1].rename(
                columns=lambda x: f'O_' + x)

            fteam.append(GoalShotCreation[0].iloc[:-1, 10:-1])
            opponent.append(GoalShotCreation[1].iloc[:-1, 10:-1])

        except Exception as e:
            print('The problem is ', e)

    elif counter == 6:
        try:
            DefensiveActions = pd.read_html(
                data.text, match="Defensive Actions", header=1)
            # DefensiveActions[0] = DefensiveActions[0].rename(columns=lambda x: f'{team_name}_' + x)
            DefensiveActions[1] = DefensiveActions[1].rename(
                columns=lambda x: f'O_' + x)

            fteam.append(DefensiveActions[0].iloc[:-1, 10:-1])
            opponent.append(DefensiveActions[1].iloc[:-1, 10:-1])

        except Exception as e:
            print('The problem is ', e)

    elif counter == 7:
        try:
            Possession = pd.read_html(data.text, match="Possession", header=1)
            # Possession[0] = Possession[0].rename(columns=lambda x: f'{team_name}_' + x)
            Possession[1] = Possession[1].rename(columns=lambda x: f'O_' + x)

            fteam.append(Possession[0].iloc[:-1, 10:-1])
            opponent.append(Possession[1].iloc[:-1, 10:-1])

        except Exception as e:
            print('The problem is ', e)

    elif counter == 8:
        try:
            MiscellaneousStats = pd.read_html(
                data.text, match="Miscellaneous Stats", header=1)
            # MiscellaneousStats[0] = MiscellaneousStats[0].rename(columns=lambda x: f'{team_name}_' + x)
            MiscellaneousStats[1] = MiscellaneousStats[1].rename(
                columns=lambda x: f'O_' + x)

            fteam.append(MiscellaneousStats[0].iloc[:-1, 10:-1])
            opponent.append(MiscellaneousStats[1].iloc[:-1, 10:-1])

        except Exception as e:
            print('The problem is ', e)
    return fteam, opponent

In [5]:
def team_stats(team_link, all_team_names, index, team_id, team_name_l):
    print(team_name_l[index])
    data = session.get(team_link)

    soup = BeautifulSoup(data.text, features="lxml")
    mdiv = soup.select('div', {'id': 'content'})[0]
    link = mdiv.find_all('a')
    link = [l.get("href") for l in link]
    link = [f"https://fbref.com" + l for l in link if l != None]

    tables_urls = [
        f'https://fbref.com/en/squads/{team_id[index]}/2023-2024/matchlogs/all_comps/schedule/{
            team_name_l[index]}-Scores-and-Fixtures-All-Competitions',
        f'https://fbref.com/en/squads/{team_id[index]}/2023-2024/matchlogs/all_comps/shooting/{
            team_name_l[index]}-Match-Logs-All-Competitions',
        f'https://fbref.com/en/squads/{team_id[index]}/2023-2024/matchlogs/all_comps/keeper/{
            team_name_l[index]}-Match-Logs-All-Competitions',
        f'https://fbref.com/en/squads/{team_id[index]}/2023-2024/matchlogs/all_comps/passing/{
            team_name_l[index]}-Match-Logs-All-Competitions',
        f'https://fbref.com/en/squads/{team_id[index]}/2023-2024/matchlogs/all_comps/passing_types/{
            team_name_l[index]}-Match-Logs-All-Competitions',
        f'https://fbref.com/en/squads/{team_id[index]}/2023-2024/matchlogs/all_comps/gca/{
            team_name_l[index]}-Match-Logs-All-Competitions',
        f'https://fbref.com/en/squads/{team_id[index]}/2023-2024/matchlogs/all_comps/defense/{
            team_name_l[index]}-Match-Logs-All-Competitions',
        f'https://fbref.com/en/squads/{team_id[index]}/2023-2024/matchlogs/all_comps/possession/{
            team_name_l[index]}-Match-Logs-All-Competitions',
        f'https://fbref.com/en/squads/{team_id[index]}/2023-2024/matchlogs/all_comps/misc/{team_name_l[index]}-Match-Logs-All-Competitions']

    if all(element in link for element in tables_urls[1:]):
        print('True. All links are in this page.')
        TeamStatistics = pd.DataFrame()
        counter = 0

        fteam = []
        opponent = []
        for url in tables_urls:
            res = session.get(url)
            fteam, opponent = get_team_data(
                res, counter, all_team_names[index], fteam, opponent)
            counter += 1
            time.sleep(15)

        fteamdf = pd.concat(fteam, axis=1)
        opponentdf = pd.concat(opponent, axis=1)
        TeamStatistics = pd.concat([fteamdf, opponentdf], axis=1)
        TeamStatistics.insert(9, "Team", all_team_names[index])
        return TeamStatistics
    else:
        return pd.DataFrame()

In [6]:
def get_next_match(df):
    null_counts = df.isnull().sum(axis=1)

    first_row_to_drop = null_counts[null_counts > 295].index[0]
    next_match = df.drop(df.index[first_row_to_drop + 1:])
    return next_match.iloc[-1:, :]

In [8]:
FutureMatche = pd.DataFrame()
NextMatches = []
for l_name, link in standings_urls.items():

    b_data = session.get(link)
    L_soup = BeautifulSoup(b_data.text, features="lxml")
    team_urls, all_team_names, team_id, team_name_l = get_team_links(
        b_data, L_soup)

    for index, team_link in enumerate(team_urls):
        data = session.get(team_link)
        soup = BeautifulSoup(data.text, features="lxml")

        TeamStats = team_stats(team_link, all_team_names,
                               index, team_id, team_name_l)
        nm = get_next_match(TeamStats)
        print(nm.shape)
        NextMatches.append(nm)

        print('*' * 100)
        time.sleep(40)
newdfs = pd.concat(NextMatches, axis=0)
newdfs.to_csv(f"Futures.csv", mode='w', index=False, encoding="utf-8")

# 2:25

Liverpool
True. All links are in this page.
(1, 308)
****************************************************************************************************
Manchester-City
True. All links are in this page.
(1, 308)
****************************************************************************************************
Arsenal
True. All links are in this page.
(1, 308)
****************************************************************************************************
Aston-Villa
True. All links are in this page.
(1, 308)
****************************************************************************************************
Tottenham-Hotspur
True. All links are in this page.
(1, 308)
****************************************************************************************************
Manchester-United
True. All links are in this page.
(1, 308)
****************************************************************************************************
West-Ham-United
True. All links are in this page.
(1, 308)
****************************************************************************************************
Newcastle-United
True. All links are in this page.
(1, 308)
****************************************************************************************************
Brighton-and-Hove-Albion
True. All links are in this page.
(1, 308)
****************************************************************************************************
Wolverhampton-Wanderers
True. All links are in this page.
(1, 308)
****************************************************************************************************
Chelsea
True. All links are in this page.
(1, 308)
****************************************************************************************************
Fulham
True. All links are in this page.
(1, 308)
****************************************************************************************************
Bournemouth
True. All links are in this page.
(1, 308)
****************************************************************************************************
Crystal-Palace
True. All links are in this page.
(1, 308)
****************************************************************************************************
Brentford
True. All links are in this page.
(1, 308)
****************************************************************************************************
Everton
True. All links are in this page.
(1, 308)
****************************************************************************************************
Nottingham-Forest
True. All links are in this page.
(1, 308)
****************************************************************************************************
Luton-Town
True. All links are in this page.
(1, 308)
****************************************************************************************************
Burnley
True. All links are in this page.
(1, 308)
****************************************************************************************************
Sheffield-United
True. All links are in this page.
(1, 308)
****************************************************************************************************
Real-Madrid
True. All links are in this page.
(1, 308)
****************************************************************************************************
Girona
True. All links are in this page.
(1, 308)
****************************************************************************************************
Barcelona
True. All links are in this page.
(1, 308)
****************************************************************************************************
Atletico-Madrid
True. All links are in this page.
(1, 308)
****************************************************************************************************
Athletic-Club
True. All links are in this page.
(1, 308)
****************************************************************************************************
Real-Betis
True. All links are in this page.
(1, 308)
****************************************************************************************************
Real-Sociedad
True. All links are in this page.
(1, 308)
****************************************************************************************************
Las-Palmas
True. All links are in this page.
(1, 308)
****************************************************************************************************
Valencia
True. All links are in this page.
(1, 308)
****************************************************************************************************
Osasuna
True. All links are in this page.
(1, 308)
****************************************************************************************************
Getafe
True. All links are in this page.
(1, 308)
****************************************************************************************************
Villarreal
True. All links are in this page.
(1, 308)
****************************************************************************************************
Alaves
True. All links are in this page.
(1, 308)
****************************************************************************************************
Sevilla
True. All links are in this page.
(1, 308)
****************************************************************************************************
Mallorca
True. All links are in this page.
(1, 308)
****************************************************************************************************
Rayo-Vallecano
True. All links are in this page.
(1, 308)
****************************************************************************************************
Celta-Vigo
True. All links are in this page.
(1, 308)
****************************************************************************************************
Cadiz
True. All links are in this page.
(1, 308)
****************************************************************************************************
Granada
True. All links are in this page.
(1, 308)
****************************************************************************************************
Almeria
True. All links are in this page.
(1, 308)
****************************************************************************************************
Bayer-Leverkusen
True. All links are in this page.
(1, 308)
****************************************************************************************************
Bayern-Munich
True. All links are in this page.
(1, 308)
****************************************************************************************************
Stuttgart
True. All links are in this page.
(1, 308)
****************************************************************************************************
Dortmund
True. All links are in this page.
(1, 308)
****************************************************************************************************
RB-Leipzig
True. All links are in this page.
(1, 308)
****************************************************************************************************
Eintracht-Frankfurt
True. All links are in this page.
(1, 308)
****************************************************************************************************
Hoffenheim
True. All links are in this page.
(1, 308)
****************************************************************************************************
Werder-Bremen
True. All links are in this page.
(1, 308)
****************************************************************************************************
Freiburg
True. All links are in this page.
(1, 308)
****************************************************************************************************
Augsburg
True. All links are in this page.
(1, 308)
****************************************************************************************************
Heidenheim
True. All links are in this page.
(1, 308)
****************************************************************************************************
Monchengladbach
True. All links are in this page.
(1, 308)
****************************************************************************************************
Wolfsburg
True. All links are in this page.
(1, 308)
****************************************************************************************************
Union-Berlin
True. All links are in this page.
(1, 308)
****************************************************************************************************
Bochum
True. All links are in this page.
(1, 308)
****************************************************************************************************
Koln
True. All links are in this page.
(1, 308)
****************************************************************************************************
Mainz-05
True. All links are in this page.
(1, 308)
****************************************************************************************************
Darmstadt-98
True. All links are in this page.
(1, 308)
****************************************************************************************************
Internazionale
True. All links are in this page.
(1, 308)
****************************************************************************************************
Juventus
True. All links are in this page.
(1, 308)
****************************************************************************************************
Milan
True. All links are in this page.
(1, 308)
****************************************************************************************************
Bologna
True. All links are in this page.
(1, 308)
****************************************************************************************************
Roma
True. All links are in this page.
(1, 308)
****************************************************************************************************
Atalanta
True. All links are in this page.
(1, 308)
****************************************************************************************************
Napoli
True. All links are in this page.
(1, 308)
****************************************************************************************************
Fiorentina
True. All links are in this page.
(1, 308)
****************************************************************************************************
Lazio
True. All links are in this page.
(1, 308)
****************************************************************************************************
Torino
True. All links are in this page.
(1, 308)
****************************************************************************************************
Monza
True. All links are in this page.
(1, 308)
****************************************************************************************************
Genoa
True. All links are in this page.
(1, 308)
****************************************************************************************************
Lecce
True. All links are in this page.
(1, 308)
****************************************************************************************************
Empoli
True. All links are in this page.
(1, 308)
****************************************************************************************************
Udinese
True. All links are in this page.
(1, 308)
****************************************************************************************************
Frosinone
True. All links are in this page.
(1, 308)
****************************************************************************************************
Hellas-Verona
True. All links are in this page.
(1, 308)
****************************************************************************************************
Cagliari
True. All links are in this page.
(1, 308)
****************************************************************************************************
Sassuolo
True. All links are in this page.
(1, 308)
****************************************************************************************************
Salernitana
True. All links are in this page.
(1, 308)
****************************************************************************************************
Paris-Saint-Germain
True. All links are in this page.
(1, 308)
****************************************************************************************************
Brest
True. All links are in this page.
(1, 308)
****************************************************************************************************
Monaco
True. All links are in this page.
(1, 308)
****************************************************************************************************
Lille
True. All links are in this page.
(1, 308)
****************************************************************************************************
Nice
True. All links are in this page.
(1, 308)
****************************************************************************************************
Lens
True. All links are in this page.
(1, 308)
****************************************************************************************************
Marseille
True. All links are in this page.
(1, 308)
****************************************************************************************************
Rennes
True. All links are in this page.
(1, 308)
****************************************************************************************************
Reims
True. All links are in this page.
(1, 308)
****************************************************************************************************
Toulouse
True. All links are in this page.
(1, 308)
****************************************************************************************************
Lyon
True. All links are in this page.
(1, 308)
****************************************************************************************************
Strasbourg
True. All links are in this page.
(1, 308)
****************************************************************************************************
Lorient
True. All links are in this page.
(1, 308)
****************************************************************************************************
Nantes
True. All links are in this page.
(1, 308)
****************************************************************************************************
Montpellier
True. All links are in this page.
(1, 308)
****************************************************************************************************
Le-Havre
True. All links are in this page.
(1, 308)
****************************************************************************************************
Metz
True. All links are in this page.
(1, 308)
****************************************************************************************************
Clermont-Foot
True. All links are in this page.
(1, 308)
****************************************************************************************************

In [18]:
data = pd.read_csv('Futures.csv')

In [19]:
data.fillna(0, axis=0, inplace=True)

In [20]:
def preprocess_data(data):
    remove_columns = ['Cmp.1', 'Att.1', 'Cmp%.1', 'Cmp.2', 'Att.2', 'Cmp%.2', 'Cmp.3', 'Att.3', 'Cmp%.3', 'xAG', 'xA', 'CrsPA', 'PrgP',
                      'Live', 'Dead', 'FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Off', 'Blocks',
                      'SCA', 'PassDead', 'Def', 'GCA', 'PassDead.1', 'Def.1', 'Def 3rd', 'Mid 3rd', 'Att 3rd', 'Tkl.1', 'Att', 'Tkl%',
                      'Lost', 'Blocks', 'Sh', 'Pass', 'Tkl+Int', 'Err', '2CrdY', 'Int', 'TklW',
                      'Recov', 'Won', 'Lost', 'Won%',
                      'SoTA', 'Save%', 'PKatt', 'PKA', 'PKsv', 'PKm', 'Cmp', 'Att', 'Cmp%',
                      'Att (GK)', 'Thr', 'Launch%', 'AvgLen', 'Att.1', 'Launch%.1', 'AvgLen.1', 'Opp', 'Stp', 'Stp%', '#OPA', 'AvgDist',
                      'O_Cmp.1', 'O_Att.1', 'O_Cmp%.1', 'O_Cmp.2', 'O_Att.2', 'O_Cmp%.2', 'O_Cmp.3', 'O_Att.3', 'O_Cmp%.3', 'O_xAG', 'O_xA', 'O_CrsPA', 'O_PrgP',
                      'Live', 'Dead', 'FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Off', 'Blocks',
                      'O_SCA', 'O_PassDead', 'O_Def', 'O_GCA', 'O_PassDead.1', 'O_Def.1', 'O_Def 3rd', 'O_Mid 3rd', 'O_Att 3rd', 'O_Tkl.1', 'O_Att', 'O_Tkl%',
                      'O_Lost', 'O_Blocks', 'O_Sh', 'O_Pass', 'O_Tkl+Int', 'O_Err', 'O_2CrdY', 'O_Int', 'O_TklW',
                      'O_Recov', 'O_Won', 'O_Lost', 'O_Won%',
                      'O_SoTA', 'O_Save%', 'O_PKatt', 'O_PKA', 'O_PKsv', 'O_PKm', 'O_Cmp', 'O_Att', 'O_Cmp%',
                      'O_Att (GK)', 'O_Thr', 'O_Launch%', 'O_AvgLen', 'O_Att.1', 'O_Launch%.1', 'O_AvgLen.1', 'O_Opp',
                      'O_Stp', 'O_Stp%', 'O_#OPA', 'O_AvgDist', 'Time', 'Round', 'G-xG', 'O_G-xG', 'np:G-xG',
                      'O_np:G-xG', 'GCA', 'O_GCA', 'Formation', 'Date', 'Result', 'Captain'
                      ]  # 145 columns
    data.drop(remove_columns, axis=1, inplace=True)
    percentage_columns = [x for x in data.columns if '%' in x]
    data.drop(percentage_columns, axis=1, inplace=True)

    # data['Duplicate'] = data.groupby('Date')['Venue'].transform(
    #     lambda x: x.duplicated(keep='first'))
    # data = data[~data['Duplicate']]
    # data.drop(columns=['Duplicate'], inplace=True)
    return data

In [21]:
def to_matchid(data):
    data['MatchID'] = None

    for i, row in data.iterrows():
        matches = []
        team = row['Team']
        opponent = row['Opponent']
        matches.append(team)
        matches.append(opponent)
        matches.sort()
        data.loc[i, 'MatchID'] = '#' + str(matches[0]) + str(matches[1])
    print(f'The shape of the dataset must be (-1, 169) : {data.shape}')

    return data

In [21]:
data = preprocess_data(data)
# data = to_matchid(data)

In [22]:
unused_cols = ['G/Sh', 'G/SoT', 'Dist', 'PK', 'xG', 'npxG', 'npxG/Sh', 'PSxG', 'PSxG+/-', 'PKatt.1', 'TotDist', 'PrgDist', 'Att.1.1',  'KP', '1/3', 'PPA',  'Att.5', 'FK.1', 'Cmp.5', 'PassLive', 'TO', 'Sh.2', 'Fld', 'PassLive.1', 'TO.1', 'Sh.1', 'Fld.1', 'Tkl', 'Att.6', 'Blocks.1', 'Sh.3', 'Clr', 'Poss.1', 'Touches', 'Def Pen', 'Def 3rd.1', 'Mid 3rd.1', 'Att 3rd.1', 'Att Pen', 'Live.1', 'Att.7', 'Succ', 'Tkld', 'Carries', 'TotDist.1', 'PrgDist.1', 'PrgC', '1/3.1', 'Mis', 'Dis', 'Rec', 'PrgR', 'Fld.2', 'Int.1', 'TklW.1', 'OG', 'Lost.1',
               ]
aunused_cols = []
for co in unused_cols:
    if co == 'Poss.1':
        continue
    conew = 'O_' + co
    aunused_cols.append(conew)
unused_cols.extend(aunused_cols)
data.drop(unused_cols, axis=1, inplace=True)
data.shape

(48, 53)

In [23]:
data.head()

,Comp,Day,Venue,GF,GA,Team,Opponent,xGA,Poss,Attendance,...,O_Off,O_Poss,O_CPA,O_CrdY,O_CrdR,O_Fls,O_Off.1,O_Crs.1,O_PKwon,O_PKcon
0,24,4,0,0.0,0.0,3,258,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,24,0,0,0.0,0.0,5,334,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,24,4,0,0.0,0.0,156,20,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,24,0,0,0.0,0.0,1,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,24,4,0,0.0,0.0,12,11,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
complete_dataset = pd.read_csv('Preprocessed/Preprocessed_data.csv')
# complete_dataset = pd.concat([co_dataset, data], axis=0)
# combined_data.shape

complete_dataset.head()

,Comp,Day,Venue,GF,GA,Team,Opponent,xGA,Poss,Attendance,...,O_In,O_Out,O_Str,O_Off,O_CPA,O_CrdY,O_CrdR,O_Fls,FTR,weight
0,24,0,1,2,0,0,0,0.3,77.0,30415.0,...,2.0,1.0,0.0,6.0,1.0,0.0,0.0,6.0,0.0,0.131153
1,24,1,0,1,1,0,1,0.6,64.0,49108.0,...,0.0,1.0,0.0,3.0,1.0,4.0,1.0,9.0,0.0,0.131579
2,24,0,1,2,1,0,2,0.5,70.0,10419.0,...,2.0,0.0,0.0,0.0,0.0,5.0,0.0,13.0,1.0,0.131817
3,24,0,0,5,0,0,3,0.7,66.0,54172.0,...,3.0,0.0,0.0,2.0,6.0,2.0,1.0,9.0,0.0,0.132486
4,4,2,1,4,0,0,4,0.3,71.0,43500.0,...,2.0,1.0,0.0,3.0,1.0,4.0,0.0,14.0,2.0,0.132679

In [25]:
def ForFutureMatches(merge_data):
    merge_data = pd.get_dummies(merge_data, columns=['Comp', 'Day', 'Venue', 'Team',
                                                     'Opponent', 'Referee'], dtype=int)
    # merge_data['weight'] = 1
    print(f'The shape of the dataset must be (-1, 2169) : {merge_data.shape}')
    return merge_data

In [26]:
dd = ForFutureMatches(complete_dataset)

The shape of the dataset must be (-1, 2169) : (31158, 2169)

In [29]:
pr = np.zeros((48, 2169))
pr = pd.DataFrame(pr, columns=dd.columns)

coln = ['Venue', 'Team', 'Opponent', 'Comp', 'Day']
for co in coln:
    for index, row in data.iterrows():
        comp = row[co]
        competition = f'{co}_' + str(int(comp))
        pr.iloc[index][competition] = 1

pr['weight'] = 1
pr.drop('FTR', axis=1, inplace=True)
pr.head()

,GF,GA,xGA,Poss,Attendance,SoT,xG.1,Saves,CS,CPA,...,Referee_1017,Referee_1021,Referee_1022,Referee_1023,Referee_1025,Referee_1026,Referee_1027,Referee_1029,Referee_1030,Referee_1031
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
pr.columns.to_list()

['GF',
 'GA',
 'xGA',
 'Poss',
 'Attendance',
 'SoT',
 'xG.1',
 'Saves',
 'CS',
 'CPA',
 'CrdY',
 'CrdR',
 'Fls',
 'Off.1',
 'Crs.1',
 'PKwon',
 'PKcon',
 'O_FK',
 'O_CS',
 'O_Cmp.4',
 'O_Ast',
 'O_Dead',
 'O_TB',
 'O_Sw',
 'O_Crs',
 'O_TI',
 'O_CK',
 'O_In',
 'O_Out',
 'O_Str',
 'O_Off',
 'O_CPA',
 'O_CrdY',
 'O_CrdR',
 'O_Fls',
 'weight',
 'Comp_1',
 'Comp_2',
 'Comp_3',
 'Comp_4',
 'Comp_5',
 'Comp_6',
 'Comp_7',
 'Comp_8',
 'Comp_9',
 'Comp_10',
 'Comp_11',
 'Comp_12',
 'Comp_13',
 'Comp_14',
 'Comp_15',
 'Comp_16',
 'Comp_17',
 'Comp_18',
 'Comp_19',
 'Comp_20',
 'Comp_21',
 'Comp_22',
 'Comp_23',
 'Comp_24',
 'Comp_25',
 'Comp_26',
 'Comp_27',
 'Comp_28',
 'Comp_29',
 'Comp_30',
 'Comp_31',
 'Comp_32',
 'Comp_33',
 'Day_0',
 'Day_1',
 'Day_2',
 'Day_3',
 'Day_4',
 'Day_5',
 'Day_6',
 'Venue_0',
 'Venue_1',
 'Venue_2',
 'Team_0',
 'Team_1',
 'Team_2',
 'Team_3',
 'Team_4',
 'Team_5',
 'Team_6',
 'Team_7',
 'Team_8',
 'Team_9',
 'Team_10',
 'Team_11',
 'Team_12',
 'Team_13',
 'Team_14',
 'Team_15',
 'Team_16',
 'Team_17',
 'Team_18',
 'Team_19',
 'Team_20',
 'Team_21',
 'Team_22',
 'Team_23',
 'Team_24',
 'Team_25',
 'Team_26',
 'Team_27',
 'Team_28',
 'Team_29',
 'Team_30',
 'Team_31',
 'Team_32',
 'Team_33',
 'Team_34',
 'Team_35',
 'Team_36',
 'Team_37',
 'Team_38',
 'Team_39',
 'Team_40',
 'Team_41',
 'Team_42',
 'Team_43',
 'Team_44',
 'Team_45',
 'Team_46',
 'Team_47',
 'Team_48',
 'Team_49',
 'Team_50',
 'Team_51',
 'Team_52',
 'Team_53',
 'Team_54',
 'Team_55',
 'Team_56',
 'Team_57',
 'Team_58',
 'Team_59',
 'Team_60',
 'Team_61',
 'Team_62',
 'Team_63',
 'Team_64',
 'Team_65',
 'Team_66',
 'Team_67',
 'Team_68',
 'Team_69',
 'Team_70',
 'Team_71',
 'Team_72',
 'Team_73',
 'Team_74',
 'Team_75',
 'Team_76',
 'Team_77',
 'Team_78',
 'Team_79',
 'Team_80',
 'Team_81',
 'Team_82',
 'Team_83',
 'Team_84',
 'Team_85',
 'Team_86',
 'Team_87',
 'Team_88',
 'Team_89',
 'Team_90',
 'Team_91',
 'Team_92',
 'Team_93',
 'Team_94',
 'Team_95',
 'Team_96',
 'Team_97',
 'Team_98',
 'Team_99',
 'Team_100',
 'Team_101',
 'Team_102',
 'Team_103',
 'Team_104',
 'Team_105',
 'Team_106',
 'Team_107',
 'Team_108',
 'Team_109',
 'Team_110',
 'Team_111',
 'Team_112',
 'Team_113',
 'Team_114',
 'Team_115',
 'Team_116',
 'Team_117',
 'Team_118',
 'Team_119',
 'Team_120',
 'Team_121',
 'Team_122',
 'Team_123',
 'Team_124',
 'Team_125',
 'Team_126',
 'Team_127',
 'Team_128',
 'Team_129',
 'Team_130',
 'Team_131',
 'Team_132',
 'Team_133',
 'Team_134',
 'Team_135',
 'Team_136',
 'Team_137',
 'Team_138',
 'Team_139',
 'Team_140',
 'Team_141',
 'Team_142',
 'Team_143',
 'Team_144',
 'Team_145',
 'Team_146',
 'Team_147',
 'Team_148',
 'Team_149',
 'Team_150',
 'Team_151',
 'Team_152',
 'Team_153',
 'Team_154',
 'Team_155',
 'Team_156',
 'Team_157',
 'Team_158',
 'Team_159',
 'Team_160',
 'Team_161',
 'Team_162',
 'Team_163',
 'Team_164',
 'Team_165',
 'Team_166',
 'Team_167',
 'Team_168',
 'Team_169',
 'Team_170',
 'Team_171',
 'Team_172',
 'Team_173',
 'Team_174',
 'Team_175',
 'Team_176',
 'Team_177',
 'Team_178',
 'Team_179',
 'Team_180',
 'Team_181',
 'Team_182',
 'Team_183',
 'Team_184',
 'Team_185',
 'Team_186',
 'Team_187',
 'Team_188',
 'Team_189',
 'Team_190',
 'Team_191',
 'Team_192',
 'Team_193',
 'Team_194',
 'Team_195',
 'Team_196',
 'Team_197',
 'Team_198',
 'Team_199',
 'Team_200',
 'Team_201',
 'Team_202',
 'Team_203',
 'Team_204',
 'Team_205',
 'Team_206',
 'Team_207',
 'Team_208',
 'Team_209',
 'Team_210',
 'Team_211',
 'Team_212',
 'Team_213',
 'Team_214',
 'Team_215',
 'Team_216',
 'Team_217',
 'Team_218',
 'Team_219',
 'Team_220',
 'Team_221',
 'Team_222',
 'Team_223',
 'Team_224',
 'Team_225',
 'Team_226',
 'Team_227',
 'Team_228',
 'Team_229',
 'Team_230',
 'Team_231',
 'Team_232',
 'Team_233',
 'Team_234',
 'Team_235',
 'Team_236',
 'Team_237',
 'Team_238',
 'Team_239',
 'Team_240',
 'Team_241',
 'Team_242',
 'Team_243',
 'Team_244',
 'Team_245',
 'Team_246',
 'Team_247',
 'Team_248',
 'Team_249',
 'Team_250',
 'Team_251',
 'Team_252',
 'Team_253',
 'Team_254',
 'Team_255',
 'Team_256',
 'Team_257',
 'Team_258',
 'Team_259',
 'Team_260',
 'Team_261',
 'Team_262',
 'Team_263',
 'Team_264',
 'Team_265',
 'Team_266',
 'Team_267',
 'Team_268',
 'Team_269',
 'Team_270',
 'Team_271',
 'Team_272',
 'Team_273',
 'Team_274',
 'Team_275',
 'Team_276',
 'Team_277',
 'Team_278',
 'Team_279',
 'Team_280',
 'Team_281',
 'Team_282',
 'Team_283',
 'Team_284',
 'Team_285',
 'Team_286',
 'Team_287',
 'Team_288',
 'Team_289',
 'Team_290',
 'Team_291',
 'Team_292',
 'Team_293',
 'Team_294',
 'Team_295',
 'Team_296',
 'Team_297',
 'Team_298',
 'Team_299',
 'Team_300',
 'Team_301',
 'Team_302',
 'Team_303',
 'Team_304',
 'Team_305',
 'Team_306',
 'Team_307',
 'Team_308',
 'Team_309',
 'Team_310',
 'Team_311',
 'Team_312',
 'Team_313',
 'Team_314',
 'Team_315',
 'Team_316',
 'Team_317',
 'Team_318',
 'Team_319',
 'Team_320',
 'Team_321',
 'Team_322',
 'Team_323',
 'Team_324',
 'Team_325',
 'Team_326',
 'Team_327',
 'Team_328',
 'Team_329',
 'Team_330',
 'Team_331',
 'Team_332',
 'Team_333',
 'Team_334',
 'Team_335',
 'Team_336',
 'Team_337',
 'Team_338',
 'Team_339',
 'Team_340',
 'Team_341',
 'Team_342',
 'Team_343',
 'Team_344',
 'Team_345',
 'Team_346',
 'Team_347',
 'Team_348',
 'Team_349',
 'Team_350',
 'Team_351',
 'Team_352',
 'Team_353',
 'Team_354',
 'Team_355',
 'Team_356',
 'Team_357',
 'Team_358',
 'Team_359',
 'Team_360',
 'Team_361',
 'Team_362',
 'Team_363',
 'Team_364',
 'Team_365',
 'Team_366',
 'Team_367',
 'Team_368',
 'Team_369',
 'Team_370',
 'Team_371',
 'Team_372',
 'Team_373',
 'Team_374',
 'Team_375',
 'Team_376',
 'Team_377',
 'Team_378',
 'Team_379',
 'Team_380',
 'Team_381',
 'Team_382',
 'Team_383',
 'Team_384',
 'Team_385',
 'Team_386',
 'Team_387',
 'Team_388',
 'Team_389',
 'Team_390',
 'Team_391',
 'Team_392',
 'Team_393',
 'Team_394',
 'Team_395',
 'Team_396',
 'Team_397',
 'Team_398',
 'Opponent_0',
 'Opponent_1',
 'Opponent_2',
 'Opponent_3',
 'Opponent_4',
 'Opponent_5',
 'Opponent_6',
 'Opponent_7',
 'Opponent_8',
 'Opponent_9',
 'Opponent_10',
 'Opponent_11',
 'Opponent_12',
 'Opponent_13',
 'Opponent_14',
 'Opponent_15',
 'Opponent_16',
 'Opponent_17',
 'Opponent_18',
 'Opponent_19',
 'Opponent_20',
 'Opponent_21',
 'Opponent_22',
 'Opponent_23',
 'Opponent_24',
 'Opponent_25',
 'Opponent_26',
 'Opponent_27',
 'Opponent_28',
 'Opponent_29',
 'Opponent_30',
 'Opponent_31',
 'Opponent_32',
 'Opponent_33',
 'Opponent_34',
 'Opponent_35',
 'Opponent_36',
 'Opponent_37',
 'Opponent_38',
 'Opponent_39',
 'Opponent_40',
 'Opponent_41',
 'Opponent_42',
 'Opponent_43',
 'Opponent_44',
 'Opponent_45',
 'Opponent_46',
 'Opponent_47',
 'Opponent_48',
 'Opponent_49',
 'Opponent_50',
 'Opponent_51',
 'Opponent_52',
 'Opponent_53',
 'Opponent_54',
 'Opponent_55',
 'Opponent_56',
 'Opponent_57',
 'Opponent_58',
 'Opponent_59',
 'Opponent_60',
 'Opponent_61',
 'Opponent_62',
 'Opponent_63',
 'Opponent_64',
 'Opponent_65',
 'Opponent_66',
 'Opponent_67',
 'Opponent_68',
 'Opponent_69',
 'Opponent_70',
 'Opponent_71',
 'Opponent_72',
 'Opponent_73',
 'Opponent_74',
 'Opponent_75',
 'Opponent_76',
 'Opponent_77',
 'Opponent_78',
 'Opponent_79',
 'Opponent_80',
 'Opponent_81',
 'Opponent_82',
 'Opponent_83',
 'Opponent_84',
 'Opponent_85',
 'Opponent_86',
 'Opponent_87',
 'Opponent_88',
 'Opponent_89',
 'Opponent_90',
 'Opponent_91',
 'Opponent_92',
 'Opponent_93',
 'Opponent_94',
 'Opponent_95',
 'Opponent_96',
 'Opponent_97',
 'Opponent_98',
 'Opponent_99',
 'Opponent_100',
 'Opponent_101',
 'Opponent_102',
 'Opponent_103',
 'Opponent_104',
 'Opponent_105',
 'Opponent_106',
 'Opponent_107',
 'Opponent_108',
 'Opponent_109',
 'Opponent_110',
 'Opponent_111',
 'Opponent_112',
 'Opponent_113',
 'Opponent_114',
 'Opponent_115',
 'Opponent_116',
 'Opponent_117',
 'Opponent_118',
 'Opponent_119',
 'Opponent_120',
 'Opponent_121',
 'Opponent_122',
 'Opponent_123',
 'Opponent_124',
 'Opponent_125',
 'Opponent_126',
 'Opponent_127',
 'Opponent_128',
 'Opponent_129',
 'Opponent_130',
 'Opponent_131',
 'Opponent_132',
 'Opponent_133',
 'Opponent_134',
 'Opponent_135',
 'Opponent_136',
 'Opponent_137',
 'Opponent_138',
 'Opponent_139',
 'Opponent_140',
 'Opponent_141',
 'Opponent_142',
 'Opponent_143',
 'Opponent_144',
 'Opponent_145',
 'Opponent_146',
 'Opponent_147',
 'Opponent_148',
 'Opponent_149',
 'Opponent_150',
 'Opponent_151',
 'Opponent_152',
 'Opponent_153',
 'Opponent_154',
 'Opponent_155',
 'Opponent_156',
 'Opponent_157',
 'Opponent_158',
 'Opponent_159',
 'Opponent_160',
 'Opponent_161',
 'Opponent_162',
 'Opponent_163',
 'Opponent_164',
 'Opponent_165',
 'Opponent_166',
 'Opponent_167',
 'Opponent_168',
 'Opponent_169',
 'Opponent_170',
 'Opponent_171',
 'Opponent_172',
 'Opponent_173',
 'Opponent_174',
 'Opponent_175',
 'Opponent_176',
 'Opponent_177',
 'Opponent_178',
 'Opponent_179',
 'Opponent_180',
 'Opponent_181',
 'Opponent_182',
 'Opponent_183',
 'Opponent_184',
 'Opponent_185',
 'Opponent_186',
 'Opponent_187',
 'Opponent_188',
 'Opponent_189',
 'Opponent_190',
 'Opponent_191',
 'Opponent_192',
 'Opponent_193',
 'Opponent_194',
 'Opponent_195',
 'Opponent_196',
 'Opponent_197',
 'Opponent_198',
 'Opponent_199',
 'Opponent_200',
 'Opponent_201',
 'Opponent_202',
 'Opponent_203',
 'Opponent_204',
 'Opponent_205',
 'Opponent_206',
 'Opponent_207',
 'Opponent_208',
 'Opponent_209',
 'Opponent_210',
 'Opponent_211',
 'Opponent_212',
 'Opponent_213',
 'Opponent_214',
 'Opponent_215',
 'Opponent_216',
 'Opponent_217',
 'Opponent_218',
 'Opponent_219',
 'Opponent_220',
 'Opponent_221',
 'Opponent_222',
 'Opponent_223',
 'Opponent_224',
 'Opponent_225',
 'Opponent_226',
 'Opponent_227',
 'Opponent_228',
 'Opponent_229',
 'Opponent_230',
 'Opponent_231',
 'Opponent_232',
 'Opponent_233',
 'Opponent_234',
 'Opponent_235',
 'Opponent_236',
 'Opponent_237',
 'Opponent_238',
 'Opponent_239',
 'Opponent_240',
 'Opponent_241',
 'Opponent_242',
 'Opponent_243',
 'Opponent_244',
 'Opponent_245',
 'Opponent_246',
 'Opponent_247',
 'Opponent_248',
 'Opponent_249',
 'Opponent_250',
 'Opponent_251',
 'Opponent_252',
 'Opponent_253',
 'Opponent_254',
 'Opponent_255',
 'Opponent_256',
 'Opponent_257',
 'Opponent_258',
 'Opponent_259',
 'Opponent_260',
 'Opponent_261',
 'Opponent_262',
 'Opponent_263',
 'Opponent_264',
 'Opponent_265',
 'Opponent_266',
 'Opponent_267',
 'Opponent_268',
 'Opponent_269',
 'Opponent_270',
 'Opponent_271',
 'Opponent_272',
 'Opponent_273',
 'Opponent_274',
 'Opponent_275',
 'Opponent_276',
 'Opponent_277',
 'Opponent_278',
 'Opponent_279',
 'Opponent_280',
 'Opponent_281',
 'Opponent_282',
 'Opponent_283',
 'Opponent_284',
 'Opponent_285',
 'Opponent_286',
 'Opponent_287',
 'Opponent_288',
 'Opponent_289',
 'Opponent_290',
 'Opponent_291',
 'Opponent_292',
 'Opponent_293',
 'Opponent_294',
 'Opponent_295',
 'Opponent_296',
 'Opponent_297',
 'Opponent_298',
 'Opponent_299',
 'Opponent_300',
 'Opponent_301',
 'Opponent_302',
 'Opponent_303',
 'Opponent_304',
 'Opponent_305',
 'Opponent_306',
 'Opponent_307',
 'Opponent_308',
 'Opponent_309',
 'Opponent_310',
 'Opponent_311',
 'Opponent_312',
 'Opponent_313',
 'Opponent_314',
 'Opponent_315',
 'Opponent_316',
 'Opponent_317',
 'Opponent_318',
 'Opponent_319',
 'Opponent_320',
 'Opponent_321',
 'Opponent_322',
 'Opponent_323',
 'Opponent_324',
 'Opponent_325',
 'Opponent_326',
 'Opponent_327',
 'Opponent_328',
 'Opponent_329',
 'Opponent_330',
 'Opponent_331',
 'Opponent_332',
 'Opponent_333',
 'Opponent_334',
 'Opponent_335',
 'Opponent_336',
 'Opponent_337',
 'Opponent_338',
 'Opponent_339',
 'Opponent_340',
 'Opponent_341',
 'Opponent_342',
 'Opponent_343',
 'Opponent_344',
 'Opponent_345',
 'Opponent_346',
 'Opponent_347',
 'Opponent_348',
 'Opponent_349',
 'Opponent_350',
 'Opponent_351',
 'Opponent_352',
 'Opponent_353',
 'Opponent_354',
 'Opponent_355',
 'Opponent_356',
 'Opponent_357',
 'Opponent_358',
 'Opponent_359',
 'Opponent_360',
 'Opponent_361',
 'Opponent_362',
 'Opponent_363',
 'Opponent_364',
 'Opponent_365',
 'Opponent_366',
 'Opponent_367',
 'Opponent_368',
 'Opponent_369',
 'Opponent_370',
 'Opponent_371',
 'Opponent_372',
 'Opponent_373',
 'Opponent_374',
 'Opponent_375',
 'Opponent_376',
 'Opponent_377',
 'Opponent_378',
 'Opponent_379',
 'Opponent_380',
 'Opponent_381',
 'Opponent_382',
 'Opponent_383',
 'Opponent_384',
 'Opponent_385',
 'Opponent_386',
 'Opponent_387',
 'Opponent_388',
 'Opponent_389',
 'Opponent_390',
 'Opponent_391',
 'Opponent_392',
 'Opponent_393',
 'Opponent_394',
 'Opponent_395',
 'Opponent_396',
 'Opponent_397',
 'Opponent_398',
 'Opponent_399',
 'Opponent_400',
 'Opponent_401',
 'Opponent_402',
 'Opponent_403',
 'Opponent_404',
 'Opponent_405',
 'Opponent_406',
 'Opponent_407',
 'Opponent_408',
 'Opponent_409',
 'Opponent_410',
 'Opponent_411',
 'Opponent_412',
 'Opponent_413',
 'Opponent_414',
 'Opponent_415',
 'Opponent_416',
 'Opponent_417',
 'Opponent_418',
 'Opponent_419',
 'Opponent_420',
 'Opponent_421',
 'Opponent_422',
 'Opponent_423',
 'Opponent_424',
 'Opponent_425',
 'Opponent_426',
 'Opponent_427',
 'Opponent_428',
 'Opponent_429',
 'Opponent_430',
 'Opponent_431',
 'Opponent_432',
 'Opponent_433',
 'Opponent_434',
 'Opponent_435',
 'Opponent_436',
 'Opponent_437',
 'Opponent_438',
 'Opponent_439',
 'Opponent_440',
 'Opponent_441',
 'Opponent_442',
 'Opponent_443',
 'Opponent_444',
 'Opponent_445',
 'Opponent_446',
 'Opponent_447',
 'Opponent_448',
 'Opponent_449',
 'Opponent_450',
 'Opponent_451',
 'Opponent_452',
 'Opponent_453',
 'Opponent_454',
 'Opponent_455',
 'Opponent_456',
 'Opponent_457',
 'Opponent_458',
 'Opponent_459',
 'Opponent_460',
 'Opponent_461',
 'Opponent_462',
 'Opponent_463',
 'Opponent_464',
 'Opponent_465',
 'Opponent_466',
 'Opponent_467',
 'Opponent_468',
 'Opponent_469',
 'Opponent_470',
 'Opponent_471',
 'Opponent_472',
 'Opponent_473',
 'Opponent_474',
 'Opponent_475',
 'Opponent_476',
 'Opponent_477',
 'Opponent_478',
 'Opponent_479',
 'Opponent_480',
 'Opponent_481',
 'Opponent_482',
 'Opponent_483',
 'Opponent_484',
 'Opponent_485',
 'Opponent_486',
 'Opponent_487',
 'Opponent_488',
 'Opponent_489',
 'Opponent_490',
 'Opponent_491',
 'Opponent_492',
 'Opponent_493',
 'Opponent_494',
 'Opponent_495',
 'Opponent_496',
 'Opponent_497',
 'Opponent_498',
 'Opponent_499',
 'Opponent_500',
 'Opponent_501',
 'Opponent_502',
 'Opponent_503',
 'Opponent_504',
 'Opponent_505',
 'Opponent_506',
 'Opponent_507',
 'Opponent_508',
 'Opponent_509',
 'Opponent_510',
 'Opponent_511',
 'Opponent_512',
 'Opponent_513',
 'Opponent_514',
 'Opponent_515',
 'Opponent_516',
 'Opponent_517',
 'Opponent_518',
 'Opponent_519',
 'Opponent_520',
 'Opponent_521',
 ...]

In [129]:
pr.to_csv('matches_for_predict.csv', mode='w', index=False, encoding="utf-8")