In [2]:
import pandas as pd

In [3]:
data0 = pd.read_csv('complete_dataset.csv')
data1 = pd.read_csv('ExtraData/2021-2022.csv')
data2 = pd.read_csv('ExtraData/2022-2023.csv')
data = pd.concat([data0, data1, data2], axis=0)
data.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Team,...,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Recov,O_Won,O_Lost.1,O_Won%
0,2017-08-12,17:30,Premier League,Matchweek 1,Sat,Away,W,2,0,Manchester City,...,8.0,12.0,8.0,0.0,0.0,1.0,42.0,13.0,13.0,50.0
1,2017-08-21,20:00,Premier League,Matchweek 2,Mon,Home,D,1,1,Manchester City,...,9.0,16.0,12.0,0.0,0.0,0.0,44.0,12.0,22.0,35.3
2,2017-08-26,12:30,Premier League,Matchweek 3,Sat,Away,W,2,1,Manchester City,...,9.0,12.0,13.0,0.0,0.0,0.0,49.0,13.0,23.0,36.1
3,2017-09-09,12:30,Premier League,Matchweek 4,Sat,Home,W,5,0,Manchester City,...,9.0,18.0,12.0,0.0,0.0,0.0,49.0,4.0,9.0,30.8
4,2017-09-13,20:45,Champions Lg,Group stage,Wed,Away,W,4,0,Manchester City,...,8.0,13.0,9.0,0.0,0.0,0.0,45.0,8.0,14.0,36.4

In [5]:
def preprocess_data(data):
    data['Result'].fillna(method='ffill', inplace=True)
    data['Result'].unique()
    remove_columns = ['Cmp.1', 'Att.1', 'Cmp%.1', 'Cmp.2', 'Att.2', 'Cmp%.2', 'Cmp.3', 'Att.3', 'Cmp%.3', 'xAG', 'xA', 'CrsPA', 'PrgP',
                      'Live', 'Dead', 'FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Off', 'Blocks',
                      'SCA', 'PassDead', 'Def', 'GCA', 'PassDead.1', 'Def.1', 'Def 3rd', 'Mid 3rd', 'Att 3rd', 'Tkl.1', 'Att', 'Tkl%',
                      'Lost', 'Blocks', 'Sh', 'Pass', 'Tkl+Int', 'Err', '2CrdY', 'Int', 'TklW',
                      'Recov', 'Won', 'Lost', 'Won%',
                      'SoTA', 'Save%', 'PKatt', 'PKA', 'PKsv', 'PKm', 'Cmp', 'Att', 'Cmp%',
                      'Att (GK)', 'Thr', 'Launch%', 'AvgLen', 'Att.1', 'Launch%.1', 'AvgLen.1', 'Opp', 'Stp', 'Stp%', '#OPA', 'AvgDist',
                      'O_Cmp.1', 'O_Att.1', 'O_Cmp%.1', 'O_Cmp.2', 'O_Att.2', 'O_Cmp%.2', 'O_Cmp.3', 'O_Att.3', 'O_Cmp%.3', 'O_xAG', 'O_xA', 'O_CrsPA', 'O_PrgP',
                      'Live', 'Dead', 'FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Off', 'Blocks',
                      'O_SCA', 'O_PassDead', 'O_Def', 'O_GCA', 'O_PassDead.1', 'O_Def.1', 'O_Def 3rd', 'O_Mid 3rd', 'O_Att 3rd', 'O_Tkl.1', 'O_Att', 'O_Tkl%',
                      'O_Lost', 'O_Blocks', 'O_Sh', 'O_Pass', 'O_Tkl+Int', 'O_Err', 'O_2CrdY', 'O_Int', 'O_TklW',
                      'O_Recov', 'O_Won', 'O_Lost', 'O_Won%',
                      'O_SoTA', 'O_Save%', 'O_PKatt', 'O_PKA', 'O_PKsv', 'O_PKm', 'O_Cmp', 'O_Att', 'O_Cmp%',
                      'O_Att (GK)', 'O_Thr', 'O_Launch%', 'O_AvgLen', 'O_Att.1', 'O_Launch%.1', 'O_AvgLen.1', 'O_Opp',
                      'O_Stp', 'O_Stp%', 'O_#OPA', 'O_AvgDist', 'Time', 'Round', 'GF', 'GA', 'G-xG', 'O_G-xG', 'np:G-xG',
                      'O_np:G-xG', 'GCA', 'O_GCA'
                      ]  # 144 columns
    data.drop(remove_columns, axis=1, inplace=True)
    percentage_columns = [x for x in data.columns if '%' in x]
    data.drop(percentage_columns, axis=1, inplace=True)
    is_null_sum_gt_20 = data.isnull().sum(axis=1) > 20  
    data = data[~is_null_sum_gt_20]
    data['Duplicate'] = data.groupby('Date')['Referee'].transform(lambda x: x.duplicated(keep='first'))
    data = data[~data['Duplicate']]
    data.drop(columns=['Duplicate'], inplace=True)
    print(f'The shape of the dataset must be (-1, 168) : {data.shape}')
    return data

In [6]:
data['Result'].fillna(method='ffill', inplace=True)
data['Result'].unique()

array(['W', 'D', 'L'], dtype=object)

In [7]:
should_remove_Team = ['Cmp.1','Att.1','Cmp%.1','Cmp.2','Att.2','Cmp%.2','Cmp.3','Att.3','Cmp%.3', 'xAG','xA','CrsPA','PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'SCA','PassDead','Def','GCA','PassDead.1','Def.1','Def 3rd','Mid 3rd','Att 3rd','Tkl.1','Att','Tkl%',
                 'Lost','Blocks','Sh','Pass','Tkl+Int','Err','2CrdY','Int','TklW',
                 'Recov','Won','Lost','Won%',
                 'SoTA','Save%','PKatt','PKA','PKsv','PKm','Cmp','Att','Cmp%',
                 'Att (GK)','Thr','Launch%','AvgLen','Att.1','Launch%.1','AvgLen.1','Opp','Stp','Stp%','#OPA','AvgDist'
                 ]
should_remove_Opponent = ['O_Cmp.1','O_Att.1','O_Cmp%.1','O_Cmp.2','O_Att.2','O_Cmp%.2','O_Cmp.3','O_Att.3','O_Cmp%.3', 'O_xAG','O_xA','O_CrsPA','O_PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'O_SCA','O_PassDead','O_Def','O_GCA','O_PassDead.1','O_Def.1','O_Def 3rd','O_Mid 3rd','O_Att 3rd','O_Tkl.1','O_Att','O_Tkl%',
                 'O_Lost','O_Blocks','O_Sh','O_Pass','O_Tkl+Int','O_Err','O_2CrdY','O_Int','O_TklW',
                 'O_Recov','O_Won','O_Lost','O_Won%',
                 'O_SoTA','O_Save%','O_PKatt','O_PKA','O_PKsv','O_PKm','O_Cmp','O_Att','O_Cmp%',
                 'O_Att (GK)','O_Thr','O_Launch%','O_AvgLen','O_Att.1','O_Launch%.1','O_AvgLen.1','O_Opp',
                 'O_Stp','O_Stp%','O_#OPA','O_AvgDist'
                 
                 ]
remove_columns = ['Cmp.1','Att.1','Cmp%.1','Cmp.2','Att.2','Cmp%.2','Cmp.3','Att.3','Cmp%.3', 'xAG','xA','CrsPA','PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'SCA','PassDead','Def','GCA','PassDead.1','Def.1','Def 3rd','Mid 3rd','Att 3rd','Tkl.1','Att','Tkl%',
                 'Lost','Blocks','Sh','Pass','Tkl+Int','Err','2CrdY','Int','TklW',
                 'Recov','Won','Lost','Won%',
                 'SoTA','Save%','PKatt','PKA','PKsv','PKm','Cmp','Att','Cmp%',
                 'Att (GK)','Thr','Launch%','AvgLen','Att.1','Launch%.1','AvgLen.1','Opp','Stp','Stp%','#OPA','AvgDist',
                 'O_Cmp.1','O_Att.1','O_Cmp%.1','O_Cmp.2','O_Att.2','O_Cmp%.2','O_Cmp.3','O_Att.3','O_Cmp%.3', 'O_xAG','O_xA','O_CrsPA','O_PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'O_SCA','O_PassDead','O_Def','O_GCA','O_PassDead.1','O_Def.1','O_Def 3rd','O_Mid 3rd','O_Att 3rd','O_Tkl.1','O_Att','O_Tkl%',
                 'O_Lost','O_Blocks','O_Sh','O_Pass','O_Tkl+Int','O_Err','O_2CrdY','O_Int','O_TklW',
                 'O_Recov','O_Won','O_Lost','O_Won%',
                 'O_SoTA','O_Save%','O_PKatt','O_PKA','O_PKsv','O_PKm','O_Cmp','O_Att','O_Cmp%',
                 'O_Att (GK)','O_Thr','O_Launch%','O_AvgLen','O_Att.1','O_Launch%.1','O_AvgLen.1','O_Opp',
                 'O_Stp','O_Stp%','O_#OPA','O_AvgDist', 'Time', 'Round', 'GF', 'GA', 'G-xG', 'O_G-xG', 'np:G-xG',
                 'O_np:G-xG', 'GCA', 'O_GCA'         
                 ] # 144 columns

In [8]:
data.drop(remove_columns, axis=1, inplace=True)
data.shape

(67304, 176)

In [9]:
percentage_columns = [x for x in data.columns if '%' in x]
data.drop(percentage_columns, axis=1, inplace=True)
data.shape

(67304, 168)

In [10]:
is_null_sum_gt_20 = data.isnull().sum(axis=1) > 20  
data = data[~is_null_sum_gt_20]
data.shape

(59796, 168)

In [11]:
data.tail()

,Date,Comp,Day,Venue,Result,Team,Opponent,xG,xGA,Poss,...,O_Fls,O_Fld.2,O_Off.1,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Lost.1
5835,2023-05-06,Ligue 2,Sat,Home,L,Niort,Metz,0.8,3.0,49.0,...,12.0,7.0,0.0,16.0,11.0,8.0,1.0,0.0,0.0,14.0
5836,2023-05-13,Ligue 2,Sat,Away,L,Niort,Bastia,1.2,2.7,57.0,...,13.0,10.0,3.0,19.0,18.0,12.0,1.0,0.0,0.0,11.0
5837,2023-05-20,Ligue 2,Sat,Home,D,Niort,Annecy,1.8,2.6,57.0,...,17.0,8.0,1.0,25.0,13.0,14.0,1.0,0.0,0.0,11.0
5838,2023-05-26,Ligue 2,Fri,Away,L,Niort,Guingamp,0.8,2.5,51.0,...,9.0,9.0,1.0,21.0,14.0,19.0,0.0,0.0,0.0,12.0
5839,2023-06-02,Ligue 2,Fri,Home,D,Niort,Quevilly-Rouen,1.5,1.1,46.0,...,16.0,9.0,2.0,13.0,19.0,13.0,0.0,0.0,0.0,7.0

In [9]:
# correlation_matrix = data.corr(numeric_only=True)
# high_correlation_features = []
# for i in range(len(correlation_matrix.columns)):
#     for j in range(i + 1, len(correlation_matrix.columns)):
#         if abs(correlation_matrix.iloc[i, j]) > 0.9:
#             high_correlation_features.append((correlation_matrix.columns[i], correlation_matrix.columns[j]))

# for feature1, feature2 in high_correlation_features:
#     if feature2 in data.columns:
#         data.drop(feature2, axis=1, inplace=True)

# print(data.shape)

(50846, 128)

In [12]:
data['Duplicate'] = data.groupby('Date')['Referee'].transform(lambda x: x.duplicated(keep='first'))
data = data[~data['Duplicate']]
print(data.shape)
data.drop(columns=['Duplicate'], inplace=True)

# This is just for testing purposes
# grouped = data.groupby('Date')
# for date, group in grouped:
    
#     print(f'For Date {date}')   
#     a = list(group["Team"])
#     b = list(group["Opponent"])
#     print(a)
#     print(b)
#     print('*' * 50)

(26787, 169)

In [13]:
data.head()

,Date,Comp,Day,Venue,Result,Team,Opponent,xG,xGA,Poss,...,O_Fls,O_Fld.2,O_Off.1,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Lost.1
0,2017-08-12,Premier League,Sat,Away,W,Manchester City,Brighton,1.9,0.3,77.0,...,6.0,8.0,6.0,8.0,12.0,8.0,0.0,0.0,1.0,13.0
1,2017-08-21,Premier League,Mon,Home,D,Manchester City,Everton,1.1,0.6,64.0,...,9.0,7.0,3.0,9.0,16.0,12.0,0.0,0.0,0.0,22.0
2,2017-08-26,Premier League,Sat,Away,W,Manchester City,Bournemouth,1.4,0.5,70.0,...,13.0,14.0,0.0,9.0,12.0,13.0,0.0,0.0,0.0,23.0
3,2017-09-09,Premier League,Sat,Home,W,Manchester City,Liverpool,2.4,0.7,66.0,...,9.0,10.0,2.0,9.0,18.0,12.0,0.0,0.0,0.0,9.0
4,2017-09-13,Champions Lg,Wed,Away,W,Manchester City,nl Feyenoord,1.3,0.3,71.0,...,14.0,9.0,3.0,8.0,13.0,9.0,0.0,0.0,0.0,14.0

In [14]:
data['MatchID'] = None
for i, row in data.iterrows():
    matches = []
    team = row['Team']
    opponent = row['Opponent']
    matches.append(team)
    matches.append(opponent)
    matches.sort()
    data.loc[i, 'MatchID'] = '#' + str(matches[0]) + str(matches[1])

data.head()

,Date,Comp,Day,Venue,Result,Team,Opponent,xG,xGA,Poss,...,O_Fld.2,O_Off.1,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Lost.1,MatchID
0,2017-08-12,Premier League,Sat,Away,W,Manchester City,Brighton,1.9,0.3,77.0,...,8.0,6.0,8.0,12.0,8.0,0.0,0.0,1.0,13.0,#Adelaide UtdSydney
1,2017-08-21,Premier League,Mon,Home,D,Manchester City,Everton,1.1,0.6,64.0,...,7.0,3.0,9.0,16.0,12.0,0.0,0.0,0.0,22.0,#Melb VictorySydney
2,2017-08-26,Premier League,Sat,Away,W,Manchester City,Bournemouth,1.4,0.5,70.0,...,14.0,0.0,9.0,12.0,13.0,0.0,0.0,0.0,23.0,#SydneyW Sydney
3,2017-09-09,Premier League,Sat,Home,W,Manchester City,Liverpool,2.4,0.7,66.0,...,10.0,2.0,9.0,18.0,12.0,0.0,0.0,0.0,9.0,#BrisbaneSydney
4,2017-09-13,Champions Lg,Wed,Away,W,Manchester City,nl Feyenoord,1.3,0.3,71.0,...,9.0,3.0,8.0,13.0,9.0,0.0,0.0,0.0,14.0,#SydneyW Sydney

In [15]:
data.groupby('MatchID').apply(lambda x: x.head())

                                         Date        Comp  Day Venue Result  \
MatchID
#1. FC NürnbergWolfsburg    1078   2017-11-18     Serie A  Sat  Home      W
                            1078   2021-11-01   DFB-Pokal  Mon  Away      W
                            1078   2022-11-20   DFB-Pokal  Sun  Away      W
#ADO Den HaagAZ Alkmaar     9541   2018-11-11  Eredivisie  Sun  Away      W
                            9559   2019-04-13  Eredivisie  Sat  Home      L
...                                       ...         ...  ...   ...    ...
#Wolvessk Slovan Bratislava 11819  2019-10-24   Europa Lg  Thu  Away      W
                            11823  2019-11-07   Europa Lg  Thu  Home      W
#Wolvestr Beşiktaş          11816  2019-10-03   Europa Lg  Thu  Away      W
                            11830  2019-12-12   Europa Lg  Thu  Home      W
#Zulte Waregemnl Vitesse    4690   2017-11-02   Europa Lg  Thu  Away      W

                                            Team              Opponent   xG  \
MatchID
#1. FC NürnbergWolfsburg    1078            Roma                 Lazio  1.6
                            1078       Wolfsburg              Freiburg  NaN
                            1078       Wolfsburg        1. FC Nürnberg  NaN
#ADO Den HaagAZ Alkmaar     9541      AZ Alkmaar          ADO Den Haag  0.9
                            9559      AZ Alkmaar          ADO Den Haag  3.7
...                                          ...                   ...  ...
#Wolvessk Slovan Bratislava 11819         Wolves  sk Slovan Bratislava  1.3
                            11823         Wolves  sk Slovan Bratislava  2.8
#Wolvestr Beşiktaş          11816         Wolves           tr Beşiktaş  0.8
                            11830         Wolves           tr Beşiktaş  2.5
#Zulte Waregemnl Vitesse    4690   Zulte Waregem            nl Vitesse  0.5

                                   xGA  Poss  ...  O_Fld.2 O_Off.1 O_Crs.1  \
MatchID                                       ...
#1. FC NürnbergWolfsburg    1078   1.2  54.0  ...      9.0     4.0    18.0
                            1078   NaN   NaN  ...     15.0     0.0    14.0
                            1078   NaN   NaN  ...      8.0     3.0    14.0
#ADO Den HaagAZ Alkmaar     9541   0.4  59.0  ...     10.0     4.0    22.0
                            9559   1.6  69.0  ...      6.0     0.0    10.0
...                                ...   ...  ...      ...     ...     ...
#Wolvessk Slovan Bratislava 11819  0.8  60.0  ...     13.0     2.0    22.0
                            11823  0.4  66.0  ...      6.0     2.0    16.0
#Wolvestr Beşiktaş          11816  0.9  38.0  ...     15.0     3.0    19.0
                            11830  0.3  52.0  ...     12.0     3.0     8.0
#Zulte Waregemnl Vitesse    4690   1.0  30.0  ...     10.0     4.0    35.0

                                  O_Int.1  O_TklW.1  O_PKwon  O_PKcon  O_OG  \
MatchID
#1. FC NürnbergWolfsburg    1078      9.0      19.0      0.0      1.0   0.0
                            1078     12.0       4.0      0.0      0.0   0.0
                            1078     14.0      12.0      0.0      0.0   0.0
#ADO Den HaagAZ Alkmaar     9541     14.0       5.0      0.0      0.0   0.0
                            9559     12.0       6.0      0.0      0.0   0.0
...                                   ...       ...      ...      ...   ...
#Wolvessk Slovan Bratislava 11819    10.0       6.0      0.0      1.0   0.0
                            11823    14.0      10.0      0.0      1.0   0.0
#Wolvestr Beşiktaş          11816    13.0      12.0      0.0      0.0   0.0
                            11830    11.0       7.0      0.0      0.0   0.0
#Zulte Waregemnl Vitesse    4690      8.0       6.0      0.0      0.0   0.0

                                   O_Lost.1                      MatchID
MatchID
#1. FC NürnbergWolfsburg    1078       20.0     #1. FC NürnbergWolfsburg
                            1078       17.0     #1. FC NürnbergWolfsburg
                            1078        9.0     #1. FC NürnbergWolfsburg
#ADO Den HaagAZ Alkmaar     9541       17.0      #ADO Den HaagAZ Alkmaar
                            9559       10.0      #ADO Den HaagAZ Alkmaar
...                                     ...                          ...
#Wolvessk Slovan Bratislava 11819      18.0  #Wolvessk Slovan Bratislava
                            11823      15.0  #Wolvessk Slovan Bratislava
#Wolvestr Beşiktaş          11816      15.0           #Wolvestr Beşiktaş
                            11830      20.0           #Wolvestr Beşiktaş
#Zulte Waregemnl Vitesse    4690       18.0     #Zulte Waregemnl Vitesse

[19461 rows x 169 columns]

In [14]:
data.to_csv('Preprocessed/Preprocessed_data.csv', index=False, mode='w', encoding='utf-8')