In [2]:
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [10]:
data = pd.read_csv('Datasets\LastSeasons\MatchesDatasetFinall.csv')
data.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Team,...,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Recov,O_Won,O_Lost.1,O_Won%
0,2022-08-06,15:00,Premier League,Matchweek 1,Sat,Away,L,1.0,4.0,Manchester City,...,24.0,3.0,15.0,0.0,0.0,0.0,56.0,13.0,11.0,54.2
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,D,2.0,2.0,Manchester City,...,11.0,10.0,20.0,0.0,0.0,0.0,54.0,23.0,17.0,57.5
2,2022-08-20,15:00,Premier League,Matchweek 3,Sat,Away,W,2.0,1.0,Manchester City,...,14.0,6.0,11.0,0.0,0.0,0.0,54.0,17.0,20.0,45.9
3,2022-08-27,12:30,Premier League,Matchweek 4,Sat,Home,L,0.0,1.0,Manchester City,...,12.0,10.0,8.0,0.0,0.0,0.0,57.0,26.0,19.0,57.8
4,2022-08-30,19:45,Premier League,Matchweek 5,Tue,Home,W,2.0,1.0,Manchester City,...,17.0,20.0,13.0,0.0,0.0,0.0,65.0,16.0,13.0,55.2

In [ ]:
pd.set_option('display.max_rows', 308)
data.dtypes

In [12]:
percentage_columns = [x for x in data.columns if '%' in x]
data.drop(percentage_columns, axis=1, inplace=True)

In [ ]:
new_data = pd.get_dummies(data, columns=['Venue', 'Day', 'Team', 'Opponent', 'Captain', 'Formation', 'Referee', 'Comp'], dtype=int)
encoded_names = new_data.columns.tolist()
encoded_names

In [14]:
new_data.drop(['Date', 'Time', 'Round', 'GF', 'GA'], axis=1, inplace=True)

In [15]:
new_data.head()

,Result,xG,xGA,Poss,Attendance,Sh,SoT,G/Sh,G/SoT,Dist,...,Comp_First Division A,Comp_La Liga,Comp_Ligue 1,Comp_Premier League,Comp_Primeira Liga,Comp_Primera Div,Comp_Pro League A,Comp_Serie A,Comp_Série A,Comp_WSL
0,L,0.5,1.5,42.0,61732.0,10.0,2.0,0.10,0.50,17.1,...,0,0,0,1,0,0,0,0,0,0
1,D,1.2,1.8,43.0,30815.0,14.0,4.0,0.14,0.50,18.1,...,0,0,0,1,0,0,0,0,0,0
2,W,0.9,0.3,38.0,30850.0,9.0,3.0,0.22,0.67,15.0,...,0,0,0,1,0,0,0,0,0,0
3,L,1.4,1.1,49.0,31196.0,17.0,4.0,0.00,0.00,13.8,...,0,0,0,1,0,0,0,0,0,0
4,W,1.1,1.1,33.0,31542.0,9.0,5.0,0.22,0.40,17.8,...,0,0,0,1,0,0,0,0,0,0

In [16]:
new_data.to_csv("Datasets/LastSeasons/PreproccessedData.csv", mode="w", index=False, encoding="utf-8")

In [3]:
data = pd.read_csv("Datasets/LastSeasons/PreproccessedData.csv")
data.head()

,Result,xG,xGA,Poss,Attendance,Sh,SoT,G/Sh,G/SoT,Dist,...,Comp_First Division A,Comp_La Liga,Comp_Ligue 1,Comp_Premier League,Comp_Primeira Liga,Comp_Primera Div,Comp_Pro League A,Comp_Serie A,Comp_Série A,Comp_WSL
0,L,0.5,1.5,42.0,61732.0,10.0,2.0,0.10,0.50,17.1,...,0,0,0,1,0,0,0,0,0,0
1,D,1.2,1.8,43.0,30815.0,14.0,4.0,0.14,0.50,18.1,...,0,0,0,1,0,0,0,0,0,0
2,W,0.9,0.3,38.0,30850.0,9.0,3.0,0.22,0.67,15.0,...,0,0,0,1,0,0,0,0,0,0
3,L,1.4,1.1,49.0,31196.0,17.0,4.0,0.00,0.00,13.8,...,0,0,0,1,0,0,0,0,0,0
4,W,1.1,1.1,33.0,31542.0,9.0,5.0,0.22,0.40,17.8,...,0,0,0,1,0,0,0,0,0,0

In [13]:
data.drop(['G-xG', 'O_G-xG', 'np:G-xG', 'O_np:G-xG', 'GCA', 'O_GCA'], axis=1, inplace=True)
data.shape

(39342, 1505)

In [78]:
means = data.mean(numeric_only=True)

In [79]:
data.fillna(means, inplace=True)

In [80]:
data.dropna(inplace=True)

In [81]:
data.shape

(39318, 1511)

In [82]:
data.isnull().sum()

Result               0
xG                   0
xGA                  0
Poss                 0
Attendance           0
                    ..
Comp_Primera Div     0
Comp_Pro League A    0
Comp_Serie A         0
Comp_Série A         0
Comp_WSL             0
Length: 1511, dtype: int64

In [83]:
X = data.drop('Result', axis=1)
y = data["Result"]

In [84]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([1, 0, 2, ..., 1, 1, 0])

In [85]:
mms = MinMaxScaler()
X = mms.fit_transform(X)
X

array([[0.125     , 0.22727273, 0.44262295, ..., 0.        , 0.        ,
        0.        ],
       [0.3       , 0.27272727, 0.45901639, ..., 0.        , 0.        ,
        0.        ],
       [0.225     , 0.04545455, 0.37704918, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.325     , 0.09090909, 0.45901639, ..., 0.        , 0.        ,
        1.        ],
       [0.25      , 0.22727273, 0.52459016, ..., 0.        , 0.        ,
        1.        ],
       [0.125     , 0.46969697, 0.2295082 , ..., 0.        , 0.        ,
        1.        ]])

In [86]:
x_train, x_test, y_train, y_test = train_test_split(X, y, random_state=42)
model = LogisticRegression()

In [87]:
model.fit(x_train, y_train)

c:\Users\moomad\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [88]:
np.unique(y_test)

array([0, 1, 2])

In [90]:
clre = accuracy_score(x_test, y_test)
clre

ValueError: Classification metrics can't handle a mix of continuous-multioutput and multiclass targets