In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('complete_dataset.csv')
data.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Team,...,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Recov,O_Won,O_Lost.1,O_Won%
0,2017-08-12,17:30,Premier League,Matchweek 1,Sat,Away,W,2,0,Manchester City,...,8.0,12.0,8.0,0.0,0.0,1.0,42.0,13.0,13.0,50.0
1,2017-08-21,20:00,Premier League,Matchweek 2,Mon,Home,D,1,1,Manchester City,...,9.0,16.0,12.0,0.0,0.0,0.0,44.0,12.0,22.0,35.3
2,2017-08-26,12:30,Premier League,Matchweek 3,Sat,Away,W,2,1,Manchester City,...,9.0,12.0,13.0,0.0,0.0,0.0,49.0,13.0,23.0,36.1
3,2017-09-09,12:30,Premier League,Matchweek 4,Sat,Home,W,5,0,Manchester City,...,9.0,18.0,12.0,0.0,0.0,0.0,49.0,4.0,9.0,30.8
4,2017-09-13,20:45,Champions Lg,Group stage,Wed,Away,W,4,0,Manchester City,...,8.0,13.0,9.0,0.0,0.0,0.0,45.0,8.0,14.0,36.4

In [3]:
def preprocess_data(data):
    data['Result'].fillna(method='ffill', inplace=True)
    data['Result'].unique()
    remove_columns = ['Cmp.1', 'Att.1', 'Cmp%.1', 'Cmp.2', 'Att.2', 'Cmp%.2', 'Cmp.3', 'Att.3', 'Cmp%.3', 'xAG', 'xA', 'CrsPA', 'PrgP',
                      'Live', 'Dead', 'FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Off', 'Blocks',
                      'SCA', 'PassDead', 'Def', 'GCA', 'PassDead.1', 'Def.1', 'Def 3rd', 'Mid 3rd', 'Att 3rd', 'Tkl.1', 'Att', 'Tkl%',
                      'Lost', 'Blocks', 'Sh', 'Pass', 'Tkl+Int', 'Err', '2CrdY', 'Int', 'TklW',
                      'Recov', 'Won', 'Lost', 'Won%',
                      'SoTA', 'Save%', 'PKatt', 'PKA', 'PKsv', 'PKm', 'Cmp', 'Att', 'Cmp%',
                      'Att (GK)', 'Thr', 'Launch%', 'AvgLen', 'Att.1', 'Launch%.1', 'AvgLen.1', 'Opp', 'Stp', 'Stp%', '#OPA', 'AvgDist',
                      'O_Cmp.1', 'O_Att.1', 'O_Cmp%.1', 'O_Cmp.2', 'O_Att.2', 'O_Cmp%.2', 'O_Cmp.3', 'O_Att.3', 'O_Cmp%.3', 'O_xAG', 'O_xA', 'O_CrsPA', 'O_PrgP',
                      'Live', 'Dead', 'FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Off', 'Blocks',
                      'O_SCA', 'O_PassDead', 'O_Def', 'O_GCA', 'O_PassDead.1', 'O_Def.1', 'O_Def 3rd', 'O_Mid 3rd', 'O_Att 3rd', 'O_Tkl.1', 'O_Att', 'O_Tkl%',
                      'O_Lost', 'O_Blocks', 'O_Sh', 'O_Pass', 'O_Tkl+Int', 'O_Err', 'O_2CrdY', 'O_Int', 'O_TklW',
                      'O_Recov', 'O_Won', 'O_Lost', 'O_Won%',
                      'O_SoTA', 'O_Save%', 'O_PKatt', 'O_PKA', 'O_PKsv', 'O_PKm', 'O_Cmp', 'O_Att', 'O_Cmp%',
                      'O_Att (GK)', 'O_Thr', 'O_Launch%', 'O_AvgLen', 'O_Att.1', 'O_Launch%.1', 'O_AvgLen.1', 'O_Opp',
                      'O_Stp', 'O_Stp%', 'O_#OPA', 'O_AvgDist', 'Time', 'Round', 'GF', 'GA', 'G-xG', 'O_G-xG', 'np:G-xG',
                      'O_np:G-xG', 'GCA', 'O_GCA'
                      ]  # 144 columns
    data.drop(remove_columns, axis=1, inplace=True)
    percentage_columns = [x for x in data.columns if '%' in x]
    data.drop(percentage_columns, axis=1, inplace=True)
    is_null_sum_gt_20 = data.isnull().sum(axis=1) > 20  
    data = data[~is_null_sum_gt_20]
    data['Duplicate'] = data.groupby('Date')['Referee'].transform(lambda x: x.duplicated(keep='first'))
    data = data[~data['Duplicate']]
    data.drop(columns=['Duplicate'], inplace=True)
    print(f'The shape of the dataset must be (-1, 168) : {data.shape}')
    return data

In [4]:
data['Result'].fillna(method='ffill', inplace=True)
data['Result'].unique()

array(['W', 'D', 'L'], dtype=object)

In [5]:
should_remove_Team = ['Cmp.1','Att.1','Cmp%.1','Cmp.2','Att.2','Cmp%.2','Cmp.3','Att.3','Cmp%.3', 'xAG','xA','CrsPA','PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'SCA','PassDead','Def','GCA','PassDead.1','Def.1','Def 3rd','Mid 3rd','Att 3rd','Tkl.1','Att','Tkl%',
                 'Lost','Blocks','Sh','Pass','Tkl+Int','Err','2CrdY','Int','TklW',
                 'Recov','Won','Lost','Won%',
                 'SoTA','Save%','PKatt','PKA','PKsv','PKm','Cmp','Att','Cmp%',
                 'Att (GK)','Thr','Launch%','AvgLen','Att.1','Launch%.1','AvgLen.1','Opp','Stp','Stp%','#OPA','AvgDist'
                 ]
should_remove_Opponent = ['O_Cmp.1','O_Att.1','O_Cmp%.1','O_Cmp.2','O_Att.2','O_Cmp%.2','O_Cmp.3','O_Att.3','O_Cmp%.3', 'O_xAG','O_xA','O_CrsPA','O_PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'O_SCA','O_PassDead','O_Def','O_GCA','O_PassDead.1','O_Def.1','O_Def 3rd','O_Mid 3rd','O_Att 3rd','O_Tkl.1','O_Att','O_Tkl%',
                 'O_Lost','O_Blocks','O_Sh','O_Pass','O_Tkl+Int','O_Err','O_2CrdY','O_Int','O_TklW',
                 'O_Recov','O_Won','O_Lost','O_Won%',
                 'O_SoTA','O_Save%','O_PKatt','O_PKA','O_PKsv','O_PKm','O_Cmp','O_Att','O_Cmp%',
                 'O_Att (GK)','O_Thr','O_Launch%','O_AvgLen','O_Att.1','O_Launch%.1','O_AvgLen.1','O_Opp',
                 'O_Stp','O_Stp%','O_#OPA','O_AvgDist'
                 
                 ]
remove_columns = ['Cmp.1','Att.1','Cmp%.1','Cmp.2','Att.2','Cmp%.2','Cmp.3','Att.3','Cmp%.3', 'xAG','xA','CrsPA','PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'SCA','PassDead','Def','GCA','PassDead.1','Def.1','Def 3rd','Mid 3rd','Att 3rd','Tkl.1','Att','Tkl%',
                 'Lost','Blocks','Sh','Pass','Tkl+Int','Err','2CrdY','Int','TklW',
                 'Recov','Won','Lost','Won%',
                 'SoTA','Save%','PKatt','PKA','PKsv','PKm','Cmp','Att','Cmp%',
                 'Att (GK)','Thr','Launch%','AvgLen','Att.1','Launch%.1','AvgLen.1','Opp','Stp','Stp%','#OPA','AvgDist',
                 'O_Cmp.1','O_Att.1','O_Cmp%.1','O_Cmp.2','O_Att.2','O_Cmp%.2','O_Cmp.3','O_Att.3','O_Cmp%.3', 'O_xAG','O_xA','O_CrsPA','O_PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'O_SCA','O_PassDead','O_Def','O_GCA','O_PassDead.1','O_Def.1','O_Def 3rd','O_Mid 3rd','O_Att 3rd','O_Tkl.1','O_Att','O_Tkl%',
                 'O_Lost','O_Blocks','O_Sh','O_Pass','O_Tkl+Int','O_Err','O_2CrdY','O_Int','O_TklW',
                 'O_Recov','O_Won','O_Lost','O_Won%',
                 'O_SoTA','O_Save%','O_PKatt','O_PKA','O_PKsv','O_PKm','O_Cmp','O_Att','O_Cmp%',
                 'O_Att (GK)','O_Thr','O_Launch%','O_AvgLen','O_Att.1','O_Launch%.1','O_AvgLen.1','O_Opp',
                 'O_Stp','O_Stp%','O_#OPA','O_AvgDist', 'Time', 'Round', 'GF', 'GA', 'G-xG', 'O_G-xG', 'np:G-xG',
                 'O_np:G-xG', 'GCA', 'O_GCA'         
                 ] # 144 columns

In [6]:
data.drop(remove_columns, axis=1, inplace=True)
data.shape

(57084, 176)

In [7]:
percentage_columns = [x for x in data.columns if '%' in x]
data.drop(percentage_columns, axis=1, inplace=True)
data.shape

(57084, 168)

In [8]:
is_null_sum_gt_20 = data.isnull().sum(axis=1) > 20  
data = data[~is_null_sum_gt_20]
data.shape

(50846, 168)

In [9]:
data.tail()

,Date,Comp,Day,Venue,Result,Team,Opponent,xG,xGA,Poss,...,O_Fls,O_Fld.2,O_Off.1,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Lost.1
57072,2024-01-21,WSL,Sun,Away,L,Bristol City,Brighton,1.3,0.6,43.0,...,14.0,7.0,1.0,22.0,12.0,16.0,0.0,0.0,0.0,3.0
57073,2024-01-28,WSL,Sun,Home,L,Bristol City,West Ham,1.0,1.5,47.0,...,8.0,8.0,2.0,10.0,9.0,16.0,0.0,0.0,0.0,12.0
57074,2024-02-03,WSL,Sat,Away,D,Bristol City,Aston Villa,0.5,3.1,29.0,...,4.0,7.0,4.0,35.0,9.0,13.0,0.0,0.0,0.0,4.0
57075,2024-02-18,WSL,Sun,Away,L,Bristol City,Leicester City,0.8,3.3,28.0,...,7.0,11.0,2.0,38.0,3.0,14.0,0.0,0.0,0.0,7.0
57076,2024-03-03,WSL,Sun,Home,L,Bristol City,Brighton,1.4,3.0,38.0,...,11.0,6.0,1.0,20.0,9.0,14.0,1.0,0.0,0.0,13.0

In [9]:
# correlation_matrix = data.corr(numeric_only=True)
# high_correlation_features = []
# for i in range(len(correlation_matrix.columns)):
#     for j in range(i + 1, len(correlation_matrix.columns)):
#         if abs(correlation_matrix.iloc[i, j]) > 0.9:
#             high_correlation_features.append((correlation_matrix.columns[i], correlation_matrix.columns[j]))

# for feature1, feature2 in high_correlation_features:
#     if feature2 in data.columns:
#         data.drop(feature2, axis=1, inplace=True)

# print(data.shape)

(50846, 128)

In [10]:
data['Duplicate'] = data.groupby('Date')['Referee'].transform(lambda x: x.duplicated(keep='first'))
data = data[~data['Duplicate']]
print(data.shape)
data.drop(columns=['Duplicate'], inplace=True)

# This is just for testing purposes
# grouped = data.groupby('Date')
# for date, group in grouped:
    
#     print(f'For Date {date}')   
#     a = list(group["Team"])
#     b = list(group["Opponent"])
#     print(a)
#     print(b)
#     print('*' * 50)

(23122, 169)

In [11]:
data.head(70)

,Date,Comp,Day,Venue,Result,Team,Opponent,xG,xGA,Poss,...,O_Fls,O_Fld.2,O_Off.1,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Lost.1
0,2017-08-12,Premier League,Sat,Away,W,Manchester City,Brighton,1.9,0.3,77.0,...,6.0,8.0,6.0,8.0,12.0,8.0,0.0,0.0,1.0,13.0
1,2017-08-21,Premier League,Mon,Home,D,Manchester City,Everton,1.1,0.6,64.0,...,9.0,7.0,3.0,9.0,16.0,12.0,0.0,0.0,0.0,22.0
2,2017-08-26,Premier League,Sat,Away,W,Manchester City,Bournemouth,1.4,0.5,70.0,...,13.0,14.0,0.0,9.0,12.0,13.0,0.0,0.0,0.0,23.0
3,2017-09-09,Premier League,Sat,Home,W,Manchester City,Liverpool,2.4,0.7,66.0,...,9.0,10.0,2.0,9.0,18.0,12.0,0.0,0.0,0.0,9.0
4,2017-09-13,Champions Lg,Wed,Away,W,Manchester City,nl Feyenoord,1.3,0.3,71.0,...,14.0,9.0,3.0,8.0,13.0,9.0,0.0,0.0,0.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2017-11-25,Premier League,Sat,Home,W,Manchester Utd,Brighton,1.2,0.5,58.0,...,9.0,9.0,1.0,17.0,14.0,14.0,0.0,0.0,1.0,14.0
78,2017-11-28,Premier League,Tue,Away,W,Manchester Utd,Watford,1.2,1.4,41.0,...,12.0,9.0,0.0,25.0,13.0,12.0,1.0,0.0,0.0,15.0
79,2017-12-02,Premier League,Sat,Away,W,Manchester Utd,Arsenal,1.8,4.7,25.0,...,11.0,10.0,4.0,26.0,5.0,14.0,0.0,0.0,0.0,24.0
80,2017-12-05,Champions Lg,Tue,Home,W,Manchester Utd,ru CSKA Moscow,2.9,0.8,56.0,...,11.0,11.0,2.0,11.0,17.0,7.0,0.0,0.0,0.0,8.0
82,2017-12-13,Premier League,Wed,Home,W,Manchester Utd,Bournemouth,1.1,0.8,57.0,...,12.0,13.0,0.0,25.0,10.0,7.0,0.0,0.0,0.0,9.0

In [12]:
data['MatchID'] = None
for i, row in data.iterrows():
    matches = []
    team = row['Team']
    opponent = row['Opponent']
    matches.append(team)
    matches.append(opponent)
    matches.sort()
    data.loc[i, 'MatchID'] = '#' + str(matches[0]) + str(matches[1])

data.head()

,Date,Comp,Day,Venue,Result,Team,Opponent,xG,xGA,Poss,...,O_Fld.2,O_Off.1,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Lost.1,MatchID
0,2017-08-12,Premier League,Sat,Away,W,Manchester City,Brighton,1.9,0.3,77.0,...,8.0,6.0,8.0,12.0,8.0,0.0,0.0,1.0,13.0,#BrightonManchester City
1,2017-08-21,Premier League,Mon,Home,D,Manchester City,Everton,1.1,0.6,64.0,...,7.0,3.0,9.0,16.0,12.0,0.0,0.0,0.0,22.0,#EvertonManchester City
2,2017-08-26,Premier League,Sat,Away,W,Manchester City,Bournemouth,1.4,0.5,70.0,...,14.0,0.0,9.0,12.0,13.0,0.0,0.0,0.0,23.0,#BournemouthManchester City
3,2017-09-09,Premier League,Sat,Home,W,Manchester City,Liverpool,2.4,0.7,66.0,...,10.0,2.0,9.0,18.0,12.0,0.0,0.0,0.0,9.0,#LiverpoolManchester City
4,2017-09-13,Champions Lg,Wed,Away,W,Manchester City,nl Feyenoord,1.3,0.3,71.0,...,9.0,3.0,8.0,13.0,9.0,0.0,0.0,0.0,14.0,#Manchester Citynl Feyenoord

In [13]:
data

,Date,Comp,Day,Venue,Result,Team,Opponent,xG,xGA,Poss,...,O_Fld.2,O_Off.1,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Lost.1,MatchID
0,2017-08-12,Premier League,Sat,Away,W,Manchester City,Brighton,1.9,0.3,77.0,...,8.0,6.0,8.0,12.0,8.0,0.0,0.0,1.0,13.0,#BrightonManchester City
1,2017-08-21,Premier League,Mon,Home,D,Manchester City,Everton,1.1,0.6,64.0,...,7.0,3.0,9.0,16.0,12.0,0.0,0.0,0.0,22.0,#EvertonManchester City
2,2017-08-26,Premier League,Sat,Away,W,Manchester City,Bournemouth,1.4,0.5,70.0,...,14.0,0.0,9.0,12.0,13.0,0.0,0.0,0.0,23.0,#BournemouthManchester City
3,2017-09-09,Premier League,Sat,Home,W,Manchester City,Liverpool,2.4,0.7,66.0,...,10.0,2.0,9.0,18.0,12.0,0.0,0.0,0.0,9.0,#LiverpoolManchester City
4,2017-09-13,Champions Lg,Wed,Away,W,Manchester City,nl Feyenoord,1.3,0.3,71.0,...,9.0,3.0,8.0,13.0,9.0,0.0,0.0,0.0,14.0,#Manchester Citynl Feyenoord
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57024,2023-11-19,WSL,Sun,Home,D,Everton,Bristol City,2.1,0.8,56.0,...,10.0,2.0,21.0,6.0,8.0,0.0,0.0,0.0,8.0,#Bristol CityEverton
57026,2023-12-10,WSL,Sun,Away,W,Everton,West Ham,0.8,1.1,47.0,...,10.0,1.0,16.0,21.0,16.0,0.0,0.0,0.0,10.0,#EvertonWest Ham
57031,2024-02-18,WSL,Sun,Home,W,Everton,West Ham,0.6,0.4,54.0,...,7.0,1.0,15.0,8.0,9.0,0.0,0.0,0.0,8.0,#EvertonWest Ham
57044,2023-11-05,WSL,Sun,Home,L,West Ham,Bristol City,1.3,1.4,63.0,...,8.0,5.0,6.0,21.0,13.0,0.0,1.0,0.0,7.0,#Bristol CityWest Ham
57051,2024-01-28,WSL,Sun,Away,W,West Ham,Bristol City,1.5,1.0,53.0,...,7.0,1.0,18.0,9.0,7.0,0.0,0.0,0.0,13.0,#Bristol CityWest Ham

In [25]:
data.groupby('MatchID').apply(lambda x: x.head())

                                         Date        Comp  Day Venue Result  \
MatchID
#ADO Den HaagAZ Alkmaar     9541   2018-11-11  Eredivisie  Sun  Away      W
                            9559   2019-04-13  Eredivisie  Sat  Home      L
                            15844  2019-09-22  Eredivisie  Sun  Away      W
                            15870  2020-03-07  Eredivisie  Sat  Home      W
                            22845  2020-10-25  Eredivisie  Sun  Away      D
...                                       ...         ...  ...   ...    ...
#Wolvessk Slovan Bratislava 11823  2019-11-07   Europa Lg  Thu  Home      W
#Wolvestr Beşiktaş          11816  2019-10-03   Europa Lg  Thu  Away      W
                            11830  2019-12-12   Europa Lg  Thu  Home      W
#Zulte Waregemnl Vitesse    4686   2017-10-19   Europa Lg  Thu  Home      D
                            4690   2017-11-02   Europa Lg  Thu  Away      W

                                            Team              Opponent   xG  \
MatchID
#ADO Den HaagAZ Alkmaar     9541      AZ Alkmaar          ADO Den Haag  0.9
                            9559      AZ Alkmaar          ADO Den Haag  3.7
                            15844     AZ Alkmaar          ADO Den Haag  2.2
                            15870     AZ Alkmaar          ADO Den Haag  2.2
                            22845     AZ Alkmaar          ADO Den Haag  2.3
...                                          ...                   ...  ...
#Wolvessk Slovan Bratislava 11823         Wolves  sk Slovan Bratislava  2.8
#Wolvestr Beşiktaş          11816         Wolves           tr Beşiktaş  0.8
                            11830         Wolves           tr Beşiktaş  2.5
#Zulte Waregemnl Vitesse    4686   Zulte Waregem            nl Vitesse  1.6
                            4690   Zulte Waregem            nl Vitesse  0.5

                                   xGA  Poss  ...  O_Fld.2 O_Off.1 O_Crs.1  \
MatchID                                       ...
#ADO Den HaagAZ Alkmaar     9541   0.4  59.0  ...     10.0     4.0    22.0
                            9559   1.6  69.0  ...      6.0     0.0    10.0
                            15844  0.3  54.0  ...     13.0     2.0    23.0
                            15870  0.3  75.0  ...      9.0     2.0     8.0
                            22845  0.6  58.0  ...      5.0     3.0    13.0
...                                ...   ...  ...      ...     ...     ...
#Wolvessk Slovan Bratislava 11823  0.4  66.0  ...      6.0     2.0    16.0
#Wolvestr Beşiktaş          11816  0.9  38.0  ...     15.0     3.0    19.0
                            11830  0.3  52.0  ...     12.0     3.0     8.0
#Zulte Waregemnl Vitesse    4686   0.5  46.0  ...     14.0     1.0    19.0
                            4690   1.0  30.0  ...     10.0     4.0    35.0

                                  O_Int.1  O_TklW.1  O_PKwon  O_PKcon  O_OG  \
MatchID
#ADO Den HaagAZ Alkmaar     9541     14.0       5.0      0.0      0.0   0.0
                            9559     12.0       6.0      0.0      0.0   0.0
                            15844     2.0      10.0      0.0      1.0   0.0
                            15870    16.0      11.0      0.0      1.0   0.0
                            22845    14.0       9.0      0.0      0.0   0.0
...                                   ...       ...      ...      ...   ...
#Wolvessk Slovan Bratislava 11823    14.0      10.0      0.0      1.0   0.0
#Wolvestr Beşiktaş          11816    13.0      12.0      0.0      0.0   0.0
                            11830    11.0       7.0      0.0      0.0   0.0
#Zulte Waregemnl Vitesse    4686     12.0       9.0      0.0      0.0   1.0
                            4690      8.0       6.0      0.0      0.0   0.0

                                   O_Lost.1                      MatchID
MatchID
#ADO Den HaagAZ Alkmaar     9541       17.0      #ADO Den HaagAZ Alkmaar
                            9559       10.0      #ADO Den HaagAZ Alkmaar
                            15844      10.0      #ADO Den HaagAZ Alkmaar
                            15870       6.0      #ADO Den HaagAZ Alkmaar
                            22845      20.0      #ADO Den HaagAZ Alkmaar
...                                     ...                          ...
#Wolvessk Slovan Bratislava 11823      15.0  #Wolvessk Slovan Bratislava
#Wolvestr Beşiktaş          11816      15.0           #Wolvestr Beşiktaş
                            11830      20.0           #Wolvestr Beşiktaş
#Zulte Waregemnl Vitesse    4686       17.0     #Zulte Waregemnl Vitesse
                            4690       18.0     #Zulte Waregemnl Vitesse

[15936 rows x 169 columns]

In [14]:
data.to_csv('Preprocessed/Preprocessed_data.csv', index=False, mode='w', encoding='utf-8')