In [1]:
import pandas as pd

In [2]:
data0 = pd.read_csv('complete_dataset.csv')
data1 = pd.read_csv('ExtraData/2017-2018.csv')
data2 = pd.read_csv('ExtraData/2018-2019.csv')
data3 = pd.read_csv('ExtraData/2019-2020.csv')
data4 = pd.read_csv('ExtraData/2020-2021.csv')
data5 = pd.read_csv('ExtraData/2021-2022.csv')
data6 = pd.read_csv('ExtraData/2022-2023.csv')
data7 = pd.read_csv('ExtraData/2023-2024.csv')
data = pd.concat([data0, data1, data2, data3, data4, data5, data6, data7], axis=0)
data.shape

(87117, 308)

In [4]:
def preprocess_data(data):
    data['Result'].fillna(method='ffill', inplace=True)
    data['Result'].unique()
    remove_columns = ['Cmp.1', 'Att.1', 'Cmp%.1', 'Cmp.2', 'Att.2', 'Cmp%.2', 'Cmp.3', 'Att.3', 'Cmp%.3', 'xAG', 'xA', 'CrsPA', 'PrgP',
                      'Live', 'Dead', 'FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Off', 'Blocks',
                      'SCA', 'PassDead', 'Def', 'GCA', 'PassDead.1', 'Def.1', 'Def 3rd', 'Mid 3rd', 'Att 3rd', 'Tkl.1', 'Att', 'Tkl%',
                      'Lost', 'Blocks', 'Sh', 'Pass', 'Tkl+Int', 'Err', '2CrdY', 'Int', 'TklW',
                      'Recov', 'Won', 'Lost', 'Won%',
                      'SoTA', 'Save%', 'PKatt', 'PKA', 'PKsv', 'PKm', 'Cmp', 'Att', 'Cmp%',
                      'Att (GK)', 'Thr', 'Launch%', 'AvgLen', 'Att.1', 'Launch%.1', 'AvgLen.1', 'Opp', 'Stp', 'Stp%', '#OPA', 'AvgDist',
                      'O_Cmp.1', 'O_Att.1', 'O_Cmp%.1', 'O_Cmp.2', 'O_Att.2', 'O_Cmp%.2', 'O_Cmp.3', 'O_Att.3', 'O_Cmp%.3', 'O_xAG', 'O_xA', 'O_CrsPA', 'O_PrgP',
                      'Live', 'Dead', 'FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Off', 'Blocks',
                      'O_SCA', 'O_PassDead', 'O_Def', 'O_GCA', 'O_PassDead.1', 'O_Def.1', 'O_Def 3rd', 'O_Mid 3rd', 'O_Att 3rd', 'O_Tkl.1', 'O_Att', 'O_Tkl%',
                      'O_Lost', 'O_Blocks', 'O_Sh', 'O_Pass', 'O_Tkl+Int', 'O_Err', 'O_2CrdY', 'O_Int', 'O_TklW',
                      'O_Recov', 'O_Won', 'O_Lost', 'O_Won%',
                      'O_SoTA', 'O_Save%', 'O_PKatt', 'O_PKA', 'O_PKsv', 'O_PKm', 'O_Cmp', 'O_Att', 'O_Cmp%',
                      'O_Att (GK)', 'O_Thr', 'O_Launch%', 'O_AvgLen', 'O_Att.1', 'O_Launch%.1', 'O_AvgLen.1', 'O_Opp',
                      'O_Stp', 'O_Stp%', 'O_#OPA', 'O_AvgDist', 'Time', 'Round', 'GF', 'GA', 'G-xG', 'O_G-xG', 'np:G-xG',
                      'O_np:G-xG', 'GCA', 'O_GCA'
                      ]  # 144 columns
    data.drop(remove_columns, axis=1, inplace=True)
    percentage_columns = [x for x in data.columns if '%' in x]
    data.drop(percentage_columns, axis=1, inplace=True)
    is_null_sum_gt_20 = data.isnull().sum(axis=1) > 20  
    data = data[~is_null_sum_gt_20]
    data['Duplicate'] = data.groupby('Date')['Referee'].transform(lambda x: x.duplicated(keep='first'))
    data = data[~data['Duplicate']]
    data.drop(columns=['Duplicate'], inplace=True)
    print(f'The shape of the dataset must be (-1, 168) : {data.shape}')
    return data

In [3]:
data['Result'].fillna(method='ffill', inplace=True)
data['Result'].unique()

array(['W', 'D', 'L'], dtype=object)

In [4]:
should_remove_Team = ['Cmp.1','Att.1','Cmp%.1','Cmp.2','Att.2','Cmp%.2','Cmp.3','Att.3','Cmp%.3', 'xAG','xA','CrsPA','PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'SCA','PassDead','Def','GCA','PassDead.1','Def.1','Def 3rd','Mid 3rd','Att 3rd','Tkl.1','Att','Tkl%',
                 'Lost','Blocks','Sh','Pass','Tkl+Int','Err','2CrdY','Int','TklW',
                 'Recov','Won','Lost','Won%',
                 'SoTA','Save%','PKatt','PKA','PKsv','PKm','Cmp','Att','Cmp%',
                 'Att (GK)','Thr','Launch%','AvgLen','Att.1','Launch%.1','AvgLen.1','Opp','Stp','Stp%','#OPA','AvgDist'
                 ]
should_remove_Opponent = ['O_Cmp.1','O_Att.1','O_Cmp%.1','O_Cmp.2','O_Att.2','O_Cmp%.2','O_Cmp.3','O_Att.3','O_Cmp%.3', 'O_xAG','O_xA','O_CrsPA','O_PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'O_SCA','O_PassDead','O_Def','O_GCA','O_PassDead.1','O_Def.1','O_Def 3rd','O_Mid 3rd','O_Att 3rd','O_Tkl.1','O_Att','O_Tkl%',
                 'O_Lost','O_Blocks','O_Sh','O_Pass','O_Tkl+Int','O_Err','O_2CrdY','O_Int','O_TklW',
                 'O_Recov','O_Won','O_Lost','O_Won%',
                 'O_SoTA','O_Save%','O_PKatt','O_PKA','O_PKsv','O_PKm','O_Cmp','O_Att','O_Cmp%',
                 'O_Att (GK)','O_Thr','O_Launch%','O_AvgLen','O_Att.1','O_Launch%.1','O_AvgLen.1','O_Opp',
                 'O_Stp','O_Stp%','O_#OPA','O_AvgDist'
                 
                 ]
remove_columns = ['Cmp.1','Att.1','Cmp%.1','Cmp.2','Att.2','Cmp%.2','Cmp.3','Att.3','Cmp%.3', 'xAG','xA','CrsPA','PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'SCA','PassDead','Def','GCA','PassDead.1','Def.1','Def 3rd','Mid 3rd','Att 3rd','Tkl.1','Att','Tkl%',
                 'Lost','Blocks','Sh','Pass','Tkl+Int','Err','2CrdY','Int','TklW',
                 'Recov','Won','Lost','Won%',
                 'SoTA','Save%','PKatt','PKA','PKsv','PKm','Cmp','Att','Cmp%',
                 'Att (GK)','Thr','Launch%','AvgLen','Att.1','Launch%.1','AvgLen.1','Opp','Stp','Stp%','#OPA','AvgDist',
                 'O_Cmp.1','O_Att.1','O_Cmp%.1','O_Cmp.2','O_Att.2','O_Cmp%.2','O_Cmp.3','O_Att.3','O_Cmp%.3', 'O_xAG','O_xA','O_CrsPA','O_PrgP',
                 'Live','Dead','FK','TB','Sw','Crs','TI','CK','In','Out','Str','Off','Blocks',
                 'O_SCA','O_PassDead','O_Def','O_GCA','O_PassDead.1','O_Def.1','O_Def 3rd','O_Mid 3rd','O_Att 3rd','O_Tkl.1','O_Att','O_Tkl%',
                 'O_Lost','O_Blocks','O_Sh','O_Pass','O_Tkl+Int','O_Err','O_2CrdY','O_Int','O_TklW',
                 'O_Recov','O_Won','O_Lost','O_Won%',
                 'O_SoTA','O_Save%','O_PKatt','O_PKA','O_PKsv','O_PKm','O_Cmp','O_Att','O_Cmp%',
                 'O_Att (GK)','O_Thr','O_Launch%','O_AvgLen','O_Att.1','O_Launch%.1','O_AvgLen.1','O_Opp',
                 'O_Stp','O_Stp%','O_#OPA','O_AvgDist', 'Time', 'Round', 'GF', 'GA', 'G-xG', 'O_G-xG', 'np:G-xG',
                 'O_np:G-xG', 'GCA', 'O_GCA'         
                 ] # 144 columns

In [5]:
data.drop(remove_columns, axis=1, inplace=True)
data.shape

(87117, 176)

In [6]:
percentage_columns = [x for x in data.columns if '%' in x]
data.drop(percentage_columns, axis=1, inplace=True)
data.shape

(87117, 168)

In [7]:
is_null_sum_gt_20 = data.isnull().sum(axis=1) > 20  
data = data[~is_null_sum_gt_20]
data.shape

(75188, 168)

In [8]:
data.tail()

,Date,Comp,Day,Venue,Result,Team,Opponent,xG,xGA,Poss,...,O_Fls,O_Fld.2,O_Off.1,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Lost.1
6059,2023-11-09,Conf Lg,Thu,Home,W,Viktoria Plzeň,hr Dinamo Zagreb,2.4,0.6,36.0,...,6.0,22.0,3.0,28.0,10.0,6.0,0.0,1.0,0.0,21.0
6062,2023-11-30,Conf Lg,Thu,Away,W,Viktoria Plzeň,xk KF Ballkani Therandë,1.6,0.6,42.0,...,8.0,22.0,2.0,17.0,12.0,16.0,0.0,0.0,0.0,23.0
6065,2023-12-14,Conf Lg,Thu,Home,W,Viktoria Plzeň,kz Astana FK,3.4,0.4,63.0,...,10.0,17.0,2.0,11.0,12.0,7.0,0.0,0.0,0.0,18.0
6072,2024-03-07,Conf Lg,Thu,Away,D,Viktoria Plzeň,ch Servette FC,0.2,0.6,52.0,...,18.0,16.0,4.0,17.0,14.0,8.0,0.0,0.0,0.0,38.0
6074,2024-03-14,Conf Lg,Thu,Home,D,Viktoria Plzeň,ch Servette FC,1.3,1.5,49.0,...,14.0,13.0,1.0,29.0,3.0,10.0,0.0,0.0,0.0,46.0

In [9]:
# correlation_matrix = data.corr(numeric_only=True)
# high_correlation_features = []
# for i in range(len(correlation_matrix.columns)):
#     for j in range(i + 1, len(correlation_matrix.columns)):
#         if abs(correlation_matrix.iloc[i, j]) > 0.9:
#             high_correlation_features.append((correlation_matrix.columns[i], correlation_matrix.columns[j]))

# for feature1, feature2 in high_correlation_features:
#     if feature2 in data.columns:
#         data.drop(feature2, axis=1, inplace=True)

# print(data.shape)

(50846, 128)

In [9]:
data['Duplicate'] = data.groupby('Date')['Referee'].transform(lambda x: x.duplicated(keep='first'))
data = data[~data['Duplicate']]
data.drop(columns=['Duplicate'], inplace=True)
print(data.shape)

# This is just for testing purposes
# grouped = data.groupby('Date')
# for date, group in grouped:
    
#     print(f'For Date {date}')   
#     a = list(group["Team"])
#     b = list(group["Opponent"])
#     print(a)
#     print(b)
#     print('*' * 50)

(32537, 168)

In [10]:
data.head()

,Date,Comp,Day,Venue,Result,Team,Opponent,xG,xGA,Poss,...,O_Fls,O_Fld.2,O_Off.1,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Lost.1
0,2017-08-12,Premier League,Sat,Away,W,Manchester City,Brighton,1.9,0.3,77.0,...,6.0,8.0,6.0,8.0,12.0,8.0,0.0,0.0,1.0,13.0
1,2017-08-21,Premier League,Mon,Home,D,Manchester City,Everton,1.1,0.6,64.0,...,9.0,7.0,3.0,9.0,16.0,12.0,0.0,0.0,0.0,22.0
2,2017-08-26,Premier League,Sat,Away,W,Manchester City,Bournemouth,1.4,0.5,70.0,...,13.0,14.0,0.0,9.0,12.0,13.0,0.0,0.0,0.0,23.0
3,2017-09-09,Premier League,Sat,Home,W,Manchester City,Liverpool,2.4,0.7,66.0,...,9.0,10.0,2.0,9.0,18.0,12.0,0.0,0.0,0.0,9.0
4,2017-09-13,Champions Lg,Wed,Away,W,Manchester City,nl Feyenoord,1.3,0.3,71.0,...,14.0,9.0,3.0,8.0,13.0,9.0,0.0,0.0,0.0,14.0

In [11]:
data['MatchID'] = None
for i, row in data.iterrows():
    matches = []
    team = row['Team']
    opponent = row['Opponent']
    matches.append(team)
    matches.append(opponent)
    matches.sort()
    data.loc[i, 'MatchID'] = '#' + str(matches[0]) + str(matches[1])

data.head()

,Date,Comp,Day,Venue,Result,Team,Opponent,xG,xGA,Poss,...,O_Fld.2,O_Off.1,O_Crs.1,O_Int.1,O_TklW.1,O_PKwon,O_PKcon,O_OG,O_Lost.1,MatchID
0,2017-08-12,Premier League,Sat,Away,W,Manchester City,Brighton,1.9,0.3,77.0,...,8.0,6.0,8.0,12.0,8.0,0.0,0.0,1.0,13.0,#PerthWestern United
1,2017-08-21,Premier League,Mon,Home,D,Manchester City,Everton,1.1,0.6,64.0,...,7.0,3.0,9.0,16.0,12.0,0.0,0.0,0.0,22.0,#Melb VictoryWestern United
2,2017-08-26,Premier League,Sat,Away,W,Manchester City,Bournemouth,1.4,0.5,70.0,...,14.0,0.0,9.0,12.0,13.0,0.0,0.0,0.0,23.0,#Melb CityWestern United
3,2017-09-09,Premier League,Sat,Home,W,Manchester City,Liverpool,2.4,0.7,66.0,...,10.0,2.0,9.0,18.0,12.0,0.0,0.0,0.0,9.0,#Wellington Phoenix FCWestern United
4,2017-09-13,Champions Lg,Wed,Away,W,Manchester City,nl Feyenoord,1.3,0.3,71.0,...,9.0,3.0,8.0,13.0,9.0,0.0,0.0,0.0,14.0,#BrisbaneWestern United

In [14]:
data.to_csv('Preprocessed/Preprocessed_data.csv', index=False, mode='w', encoding='utf-8')