In [18]:
import pandas as pd
import os
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [19]:
hame = []
directory = "D:\Prog\Python Codes\Football\Fotmob"
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        filepath = os.path.join(directory, filename)
        league_names = filename.split("_20")[0]
        df = pd.read_csv(filepath)
        df["league_name"] = league_names
        hame.append(df)
data = pd.concat(hame, axis=0)
data.head()

,match_date,league_name,matchid,home_team,away_team,home_probability_win,draw_probability,away_probability_win,home_goals,away_goals,...,away_interceptions,away_blocks,away_clearances,away_keeper_save,away_duels_won,away_geround_duels_won,away_aerial_duels_won,away_successful_dribbles,away_yellow_cards,away_red_cards
0,2021-04-14,afc_champions_league,3570132,Persepolis,Al-Wahda,0.802575,0.077706,0.119719,1,0,...,11,2,10,2,40,40,47,33,2,0
1,2021-04-14,afc_champions_league,3535208,Pakhtakor Tashkent,Tractor,0.396330,0.182228,0.421442,3,3,...,11,2,13,2,43,48,42,54,4,0
2,2021-04-14,afc_champions_league,3535235,FC Goa,Al-Rayyan,0.370152,0.231029,0.398820,0,0,...,5,1,9,1,39,49,71,76,3,0
3,2021-04-14,afc_champions_league,3571780,Al-Sadd,Foolad Khouzestan,0.528834,0.161883,0.309284,1,1,...,13,6,20,3,52,47,50,40,2,0
4,2021-04-14,afc_champions_league,3535229,Al-Wehdat,Al Nassr FC,0.282160,0.382213,0.335627,0,0,...,11,0,2,1,33,35,46,14,0,0

In [20]:
df = data[['league_name', 'home_team', 'away_team', 'home_fouls_commited', 'away_fouls_commited',
           'home_tackles_won', 'away_tackles_won', 'home_yellow_cards', 'away_yellow_cards']]
df['yellow_cards'] = df['home_yellow_cards'] + df['away_yellow_cards']
df['fouls'] = df['home_fouls_commited'] + df['away_fouls_commited']
df['tackles_won'] = df['home_tackles_won'] + df['away_tackles_won']
df.drop(['home_fouls_commited', 'away_fouls_commited', 'home_tackles_won', 'away_tackles_won', 'home_yellow_cards', 'away_yellow_cards'], axis=1, inplace=True)
df.head()

C:\Users\moomad\AppData\Local\Temp\ipykernel_5920\3867151535.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['yellow_cards'] = df['home_yellow_cards'] + df['away_yellow_cards']
C:\Users\moomad\AppData\Local\Temp\ipykernel_5920\3867151535.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fouls'] = df['home_fouls_commited'] + df['away_fouls_commited']
C:\Users\moomad\AppData\Local\Temp\ipykernel_5920\3867151535.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tackles_won'] = df['home_tackles_won'] + df['away_tackles_won']
C:\Users\moomad\AppData\Local\Temp\ipykernel_5920\3867151535.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['home_fouls_commited', 'away_fouls_commited', 'home_tackles_won', 'away_tackles_won', 'home_yellow_cards', 'away_yellow_cards'], axis=1, inplace=True)

,league_name,home_team,away_team,yellow_cards,fouls,tackles_won
0,afc_champions_league,Persepolis,Al-Wahda,3,24,138
1,afc_champions_league,Pakhtakor Tashkent,Tractor,6,29,110
2,afc_champions_league,FC Goa,Al-Rayyan,5,21,129
3,afc_champions_league,Al-Sadd,Foolad Khouzestan,2,38,137
4,afc_champions_league,Al-Wehdat,Al Nassr FC,0,19,134

In [21]:
y = df.yellow_cards
x = df.drop('yellow_cards', axis=1)
mms = MinMaxScaler()
x.iloc[:,3:] = mms.fit_transform(x.iloc[:,3:])
x = pd.get_dummies(x, columns=['league_name', 'home_team', 'away_team'], dtype=int)

In [22]:
x.head()

,fouls,tackles_won,league_name_A_league_australia,league_name_A_league_australia_women,league_name_Allsvenskan_sweeden,league_name_Ekstraklasa_poland,league_name_Eredivisie_netherland,league_name_Frauen_Bundesliga,league_name_HNL_croatia,league_name_MLS_USA,...,away_team_Zanaco,away_team_Zenit St. Petersburg,away_team_Zhejiang Professional,away_team_Zorya,away_team_Zulte Waregem,away_team_Zulte-Waregem,away_team_Ñublense,away_team_Örebro,away_team_Östersunds FK,away_team_Ümraniyespor
0,0.333333,0.641618,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.416667,0.479769,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0.283333,0.589595,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.566667,0.635838,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0.250000,0.618497,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=23)
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
acc = accuracy_score(y_test, y_pred)
acc

c:\Users\moomad\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.3575476558475013

In [26]:
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [30]:
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.models import Sequential
model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(x_train.shape[1],)))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.5))
model.add(BatchNormalization())
model.add(Dense(16, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy',
              metrics=['accuracy'])
history = model.fit(x_train, y_train, epochs=20,
                    batch_size=32, validation_data=(x_test, y_test),
                    # class_weight=weight_dict
                    )

Epoch 1/20
WARNING:tensorflow:From c:\Users\moomad\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\moomad\anaconda3\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

1820/1820 [==============================] - 43s 17ms/step - loss: 2.0354 - accuracy: 0.3011 - val_loss: 1.8875 - val_accuracy: 0.3393
Epoch 2/20
1820/1820 [==============================] - 26s 14ms/step - loss: 1.8814 - accuracy: 0.3343 - val_loss: 1.8544 - val_accuracy: 0.3487
Epoch 3/20
1820/1820 [==============================] - 32s 18ms/step - loss: 1.8487 - accuracy: 0.3536 - val_loss: 1.8358 - val_accuracy: 0.3566
Epoch 4/20
 764/1820 [===========>..................] - ETA: 13s - loss: 1.8199 - accuracy: 0.3633

KeyboardInterrupt: